{
	"alias": "FEDORA-2022-5aee32fbab",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 2027730,
			"feedback": [
				{
					"bug_id": 2027730,
					"comment": {
						"id": 2359584,
						"karma": 1,
						"testcase_feedback": [
							{
								"comment_id": 2359584,
								"testcase": {
									"id": 142,
									"name": "QA:Testcase 389 ds base setup testcase"
								},
								"testcase_id": 142
							},
							{
								"comment_id": 2359584,
								"testcase": {
									"id": 143,
									"name": "QA:Testcase Create normalized dn cache testcase"
								},
								"testcase_id": 143
							},
							{
								"comment_id": 2359584,
								"testcase": {
									"id": 144,
									"name": "QA:Testcase Create normalized dn cache testcase2"
								},
								"testcase_id": 144
							}
						],
						"text": "Tested with ipa-backup/uninstall/ipa-restore, works well",
						"timestamp": "2022-01-25 16:18:42",
						"update_id": 369615,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/1cbca7b0643a627efade96d828034c6e658415d5bb72e57fc57e295efae8b689?s=24&d=retro",
							"email": "frenaud@redhat.com",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "gitfreeipa"
								}
							],
							"id": 3071,
							"name": "frenaud",
							"openid": "frenaud.id.fedoraproject.org"
						},
						"user_id": 3071
					},
					"comment_id": 2359584,
					"karma": 1
				},
				{
					"bug_id": 2027730,
					"comment": {
						"id": 2382564,
						"karma": -1,
						"testcase_feedback": [
							{
								"comment_id": 2382564,
								"testcase": {
									"id": 142,
									"name": "QA:Testcase 389 ds base setup testcase"
								},
								"testcase_id": 142
							},
							{
								"comment_id": 2382564,
								"testcase": {
									"id": 143,
									"name": "QA:Testcase Create normalized dn cache testcase"
								},
								"testcase_id": 143
							},
							{
								"comment_id": 2382564,
								"testcase": {
									"id": 144,
									"name": "QA:Testcase Create normalized dn cache testcase2"
								},
								"testcase_id": 144
							}
						],
						"text": "So, couple things:\n\n* This was actually pushed stable successfully: it's [right there in the stable updates tree](https://dl.fedoraproject.org/pub/fedora/linux/updates/35/Everything/x86_64/Packages/3/). Bodhi got out of whack somehow.\n* This actually breaks FreeIPA upgrades and should not have been pushed stable at all. I'm investigating why ATM.",
						"timestamp": "2022-01-27 18:06:54",
						"update_id": 369615,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/0e6c01c694d74afb0cbb65bc1be91950111503818caf492c0938dc2b97c48c41?s=24&d=retro",
							"email": "awilliam@redhat.com",
							"groups": [
								{
									"name": "proventesters"
								},
								{
									"name": "provenpackager"
								},
								{
									"name": "packager"
								},
								{
									"name": "qa-tools-sig"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "news"
								},
								{
									"name": "gittriage"
								},
								{
									"name": "sysadmin"
								},
								{
									"name": "gitspin-kickstarts"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "gitgeneric-release"
								},
								{
									"name": "yak_farmers"
								},
								{
									"name": "triagers"
								},
								{
									"name": "qa"
								},
								{
									"name": "sysadmin-qa"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "gitmkinitrd"
								},
								{
									"name": "qa-admin"
								},
								{
									"name": "sysadmin-main"
								},
								{
									"name": "common-issues-triage"
								},
								{
									"name": "aws-qa"
								},
								{
									"name": "gitfedora-project-schedule"
								},
								{
									"name": "change-wranglers"
								},
								{
									"name": "fedora-ci-admins"
								},
								{
									"name": "program-management"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 302,
							"name": "adamwill",
							"openid": "adamwill.id.fedoraproject.org"
						},
						"user_id": 302
					},
					"comment_id": 2382564
				},
				{
					"bug_id": 2027730,
					"comment": {
						"id": 2383012,
						"testcase_feedback": [
							{
								"comment_id": 2383012,
								"testcase": {
									"id": 142,
									"name": "QA:Testcase 389 ds base setup testcase"
								},
								"testcase_id": 142
							},
							{
								"comment_id": 2383012,
								"testcase": {
									"id": 143,
									"name": "QA:Testcase Create normalized dn cache testcase"
								},
								"testcase_id": 143
							},
							{
								"comment_id": 2383012,
								"testcase": {
									"id": 144,
									"name": "QA:Testcase Create normalized dn cache testcase2"
								},
								"testcase_id": 144
							}
						],
						"text": "Cause of the problem turns out to be https://bugzilla.redhat.com/show_bug.cgi?id=2047323 , @mreynolds is getting that fixed now.",
						"timestamp": "2022-01-27 21:22:46",
						"update_id": 369615,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/0e6c01c694d74afb0cbb65bc1be91950111503818caf492c0938dc2b97c48c41?s=24&d=retro",
							"email": "awilliam@redhat.com",
							"groups": [
								{
									"name": "proventesters"
								},
								{
									"name": "provenpackager"
								},
								{
									"name": "packager"
								},
								{
									"name": "qa-tools-sig"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "news"
								},
								{
									"name": "gittriage"
								},
								{
									"name": "sysadmin"
								},
								{
									"name": "gitspin-kickstarts"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "gitgeneric-release"
								},
								{
									"name": "yak_farmers"
								},
								{
									"name": "triagers"
								},
								{
									"name": "qa"
								},
								{
									"name": "sysadmin-qa"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "gitmkinitrd"
								},
								{
									"name": "qa-admin"
								},
								{
									"name": "sysadmin-main"
								},
								{
									"name": "common-issues-triage"
								},
								{
									"name": "aws-qa"
								},
								{
									"name": "gitfedora-project-schedule"
								},
								{
									"name": "change-wranglers"
								},
								{
									"name": "fedora-ci-admins"
								},
								{
									"name": "program-management"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 302,
							"name": "adamwill",
							"openid": "adamwill.id.fedoraproject.org"
						},
						"user_id": 302
					},
					"comment_id": 2383012
				},
				{
					"bug_id": 2027730,
					"comment": {
						"id": 2392277,
						"karma": 1,
						"testcase_feedback": [
							{
								"comment_id": 2392277,
								"testcase": {
									"id": 142,
									"name": "QA:Testcase 389 ds base setup testcase"
								},
								"testcase_id": 142
							},
							{
								"comment_id": 2392277,
								"testcase": {
									"id": 143,
									"name": "QA:Testcase Create normalized dn cache testcase"
								},
								"testcase_id": 143
							},
							{
								"comment_id": 2392277,
								"testcase": {
									"id": 144,
									"name": "QA:Testcase Create normalized dn cache testcase2"
								},
								"testcase_id": 144
							}
						],
						"text": "The update properly fixes the winsync issue #[5079](https://github.com/389ds/389-ds-base/issues/5079), as can be seen in IPA's nightly PR #[1481](https://github.com/freeipa-pr-ci2/freeipa/pull/1481): [test report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/215eeb26-8433-11ec-b3e7-fa163e67bee2/report.html), using the following [packages](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/215eeb26-8433-11ec-b3e7-fa163e67bee2/installed_packages/installed_packages_master.log.gz): 389-ds-base-2.0.14-1.fc35.x86_64",
						"timestamp": "2022-02-03 19:42:07",
						"update_id": 374646,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/1cbca7b0643a627efade96d828034c6e658415d5bb72e57fc57e295efae8b689?s=24&d=retro",
							"email": "frenaud@redhat.com",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "gitfreeipa"
								}
							],
							"id": 3071,
							"name": "frenaud",
							"openid": "frenaud.id.fedoraproject.org"
						},
						"user_id": 3071
					},
					"comment_id": 2392277
				}
			],
			"title": "SELinux is preventing ns-slapd access to /dev/shm/slapd-IPA-TEST/DBVERSION",
			"bugzilla": {
				"bug_id": "2027730",
				"creation_ts": "2021-11-30 14:11:42 +0000",
				"short_desc": "SELinux is preventing ns-slapd access to /dev/shm/slapd-IPA-TEST/DBVERSION",
				"delta_ts": "2022-02-04 01:22:28 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Triaged",
				"priority": "medium",
				"bug_severity": "high",
				"external_bugs": {
					"text": "IDMDS-1906",
					"name": "Red Hat Issue Tracker"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "15723157",
						"comment_count": "0",
						"who": {
							"text": "frenaud",
							"name": "Florence Blanc-Renaud"
						},
						"bug_when": "2021-11-30 14:11:42 +0000",
						"thetext": "Description of problem:\nThe command ipa-restore is failing in Fedora 35 with updates-testing enabled.\nThe command fails when restarting the directory server and the logs show that access to the file /dev/shm/slapd-IPA-TEST/DBVERSION is denied.\n\nVersion-Release number of selected component (if applicable):\n389-ds-base-2.0.11-1.fc35.x86_64\nfreeipa-server-4.9.8-1.fc35.x86_64\nselinux-policy-35.6-1.fc35.noarch\n\n\nHow reproducible:\nAll the time\n\nSteps to Reproduce:\n1. enable updates-testing, install freeipa-server packages\n2. ipa-server-install --domain ipa.test --realm IPA.TEST -a $PASSWORD -p $PASSWORD -U\n3. ipa-backup\n4. ipa-server-install --uninstall -U\n5. ipa-restore /path/to/backup/from/step/3\n\nActual results:\n# ipa-restore /var/lib/ipa/backup/ipa-full-2021-11-30-08-47-14\nPreparing restore from /var/lib/ipa/backup/ipa-full-2021-11-30-08-47-14 on ci-vm-10-0-137-67.hosted.upshift.rdu2.redhat.com\nPerforming FULL restore from FULL backup\nTemporary setting umask to 022\nRestoring data will overwrite existing live data. Continue to restore? [no]: yes\nEach master will individually need to be re-initialized or\nre-created from this one. The replication agreements on\nmasters running IPA 3.1 or earlier will need to be manually\nre-enabled. See the man page for details.\nDisabling all replication.\nUnable to get connection, skipping disabling agreements: directory server instance is not running/configured\nStopping IPA services\nRestoring files\nSystemwide CA database updated.\nRestoring from userRoot in IPA-TEST\nRestoring from ipaca in IPA-TEST\nRestarting GSS-proxy\nStarting IPA services\nRestoring umask to 18\nCalledProcessError(Command ['/usr/sbin/ipactl', 'start'] returned non-zero exit status 1: \"Existing service file detected!\\nAssuming stale, cleaning and proceeding\\nFailed to start Directory Service: CalledProcessError(Command ['/bin/systemctl', 'start', 'dirsrv@IPA-TEST.service'] returned non-zero exit status 1)\\n\")\nThe ipa-restore command failed. See /var/log/iparestore.log for more information\n\n\nExpected results:\nRestore should succeed\n\nAdditional info:\n\nTail of /var/log/iparestore.log:\n2021-11-30T13:50:02Z INFO Starting IPA services\n2021-11-30T13:50:02Z DEBUG Starting external process\n2021-11-30T13:50:02Z DEBUG args=['/usr/sbin/ipactl', 'start']\n2021-11-30T13:50:11Z DEBUG Process finished, return code=1\n2021-11-30T13:50:11Z DEBUG stdout=Starting Directory Service\n\n2021-11-30T13:50:11Z DEBUG stderr=Existing service file detected!\nAssuming stale, cleaning and proceeding\nFailed to start Directory Service: CalledProcessError(Command ['/bin/systemctl', 'start', 'dirsrv@IPA-TEST.service'] returned non-zero exit status 1)\n\n2021-11-30T13:50:11Z INFO Restoring umask to 18\n2021-11-30T13:50:11Z DEBUG   File \"/usr/lib/python3.10/site-packages/ipapython/admintool.py\", line 180, in execute\n    return_value = self.run()\n  File \"/usr/lib/python3.10/site-packages/ipaserver/install/ipa_restore.py\", line 459, in run\n    run([paths.IPACTL, 'start'])\n  File \"/usr/lib/python3.10/site-packages/ipapython/ipautil.py\", line 598, in run\n    raise CalledProcessError(\n\n2021-11-30T13:50:11Z DEBUG The ipa-restore command failed, exception: CalledProcessError: CalledProcessError(Command ['/usr/sbin/ipactl', 'start'] returned non-zero exit status 1: \"Existing service file detected!\\nAssuming stale, cleaning and proceeding\\nFailed to start Directory Service: CalledProcessError(Command ['/bin/systemctl', 'start', 'dirsrv@IPA-TEST.service'] returned non-zero exit status 1)\\n\")\n2021-11-30T13:50:11Z ERROR CalledProcessError(Command ['/usr/sbin/ipactl', 'start'] returned non-zero exit status 1: \"Existing service file detected!\\nAssuming stale, cleaning and proceeding\\nFailed to start Directory Service: CalledProcessError(Command ['/bin/systemctl', 'start', 'dirsrv@IPA-TEST.service'] returned non-zero exit status 1)\\n\")\n2021-11-30T13:50:11Z ERROR The ipa-restore command failed. See /var/log/iparestore.log for more information\n\n\nIn /var/log/dirsrv/slapd-IPA-TEST/errors:\n[30/Nov/2021:08:50:10.242486123 -0500] - ERR - bdb_version_write - Could not open file \"/dev/shm/slapd-IPA-TEST/DBVERSION\" for writing Netscape Portable Runtime -5966 (Access Denied.)\n\nOutput of ausearch -m AVC:\n----\ntime->Tue Nov 30 08:50:10 2021\ntype=AVC msg=audit(1638280210.241:2626): avc:  denied  { open } for  pid=53250 comm=\"ns-slapd\" path=\"/dev/shm/slapd-IPA-TEST/DBVERSION\" dev=\"tmpfs\" ino=24 scontext=system_u:system_r:dirsrv_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=file permissive=0\n----\ntime->Tue Nov 30 08:50:10 2021\ntype=AVC msg=audit(1638280210.244:2627): avc:  denied  { read } for  pid=53250 comm=\"ns-slapd\" name=\"slapd-IPA-TEST\" dev=\"tmpfs\" ino=20 scontext=system_u:system_r:dirsrv_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=dir permissive=0\n----\ntime->Tue Nov 30 08:50:10 2021\ntype=AVC msg=audit(1638280210.248:2628): avc:  denied  { read } for  pid=53250 comm=\"ns-slapd\" name=\"slapd-IPA-TEST\" dev=\"tmpfs\" ino=20 scontext=system_u:system_r:dirsrv_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=dir permissive=0\n----\ntime->Tue Nov 30 08:50:10 2021\ntype=AVC msg=audit(1638280210.250:2629): avc:  denied  { read } for  pid=53250 comm=\"ns-slapd\" name=\"slapd-IPA-TEST\" dev=\"tmpfs\" ino=20 scontext=system_u:system_r:dirsrv_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=dir permissive=0\n----\ntime->Tue Nov 30 08:50:10 2021\ntype=AVC msg=audit(1638280210.250:2630): avc:  denied  { write } for  pid=53250 comm=\"ns-slapd\" name=\"slapd-IPA-TEST\" dev=\"tmpfs\" ino=20 scontext=system_u:system_r:dirsrv_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=dir permissive=0\n\n\n\nWhen running in permissive mode, the following AVCs are logged:\n----\ntime->Tue Nov 30 09:04:23 2021\ntype=AVC msg=audit(1638281063.162:3233): avc:  denied  { open } for  pid=54205 comm=\"ns-slapd\" path=\"/dev/shm/slapd-IPA-TEST/DBVERSION\" dev=\"tmpfs\" ino=33 scontext=system_u:system_r:dirsrv_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=file permissive=1\n----\ntime->Tue Nov 30 09:04:23 2021\ntype=AVC msg=audit(1638281063.162:3234): avc:  denied  { read } for  pid=54205 comm=\"ns-slapd\" name=\"slapd-IPA-TEST\" dev=\"tmpfs\" ino=29 scontext=system_u:system_r:dirsrv_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=dir permissive=1\n----\ntime->Tue Nov 30 09:04:23 2021\ntype=AVC msg=audit(1638281063.165:3235): avc:  denied  { write } for  pid=54205 comm=\"ns-slapd\" name=\"slapd-IPA-TEST\" dev=\"tmpfs\" ino=29 scontext=system_u:system_r:dirsrv_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=dir permissive=1\n----\ntime->Tue Nov 30 09:04:23 2021\ntype=AVC msg=audit(1638281063.165:3236): avc:  denied  { add_name } for  pid=54205 comm=\"ns-slapd\" name=\"__db.001\" scontext=system_u:system_r:dirsrv_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=dir permissive=1\n----\ntime->Tue Nov 30 09:04:23 2021\ntype=AVC msg=audit(1638281063.165:3237): avc:  denied  { create } for  pid=54205 comm=\"ns-slapd\" name=\"__db.001\" scontext=system_u:system_r:dirsrv_t:s0 tcontext=system_u:object_r:user_tmp_t:s0 tclass=file permissive=1\n----\ntime->Tue Nov 30 09:04:23 2021\ntype=AVC msg=audit(1638281063.165:3238): avc:  denied  { open } for  pid=54205 comm=\"ns-slapd\" path=\"/dev/shm/slapd-IPA-TEST/__db.001\" dev=\"tmpfs\" ino=39 scontext=system_u:system_r:dirsrv_t:s0 tcontext=system_u:object_r:user_tmp_t:s0 tclass=file permissive=1\n----\ntime->Tue Nov 30 09:04:23 2021\ntype=AVC msg=audit(1638281063.228:3239): avc:  denied  { map } for  pid=54205 comm=\"ns-slapd\" path=\"/dev/shm/slapd-IPA-TEST/__db.001\" dev=\"tmpfs\" ino=39 scontext=system_u:system_r:dirsrv_t:s0 tcontext=system_u:object_r:user_tmp_t:s0 tclass=file permissive=1\n----\ntime->Tue Nov 30 09:05:26 2021\ntype=AVC msg=audit(1638281126.515:3323): avc:  denied  { open } for  pid=54730 comm=\"ns-slapd\" path=\"/dev/shm/slapd-IPA-TEST/DBVERSION\" dev=\"tmpfs\" ino=33 scontext=system_u:system_r:dirsrv_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=file permissive=1\n----\ntime->Tue Nov 30 09:05:26 2021\ntype=AVC msg=audit(1638281126.515:3324): avc:  denied  { read } for  pid=54730 comm=\"ns-slapd\" name=\"slapd-IPA-TEST\" dev=\"tmpfs\" ino=29 scontext=system_u:system_r:dirsrv_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=dir permissive=1\n----\ntime->Tue Nov 30 09:05:26 2021\ntype=AVC msg=audit(1638281126.516:3325): avc:  denied  { open } for  pid=54730 comm=\"ns-slapd\" path=\"/dev/shm/slapd-IPA-TEST/__db.003\" dev=\"tmpfs\" ino=41 scontext=system_u:system_r:dirsrv_t:s0 tcontext=system_u:object_r:user_tmp_t:s0 tclass=file permissive=1\n----\ntime->Tue Nov 30 09:05:26 2021\ntype=AVC msg=audit(1638281126.517:3326): avc:  denied  { map } for  pid=54730 comm=\"ns-slapd\" path=\"/dev/shm/slapd-IPA-TEST/__db.001\" dev=\"tmpfs\" ino=39 scontext=system_u:system_r:dirsrv_t:s0 tcontext=system_u:object_r:user_tmp_t:s0 tclass=file permissive=1\n\n\nOutput of audit2allow:\n#============= dirsrv_t ==============\nallow dirsrv_t user_tmp_t:dir { add_name read write };\nallow dirsrv_t user_tmp_t:file { create open };\n\n#!!!! This avc can be allowed using the boolean 'domain_can_mmap_files'\nallow dirsrv_t user_tmp_t:file map;"
					},
					{
						"isprivate": "0",
						"commentid": "15776555",
						"comment_count": "1",
						"who": {
							"text": "frenaud",
							"name": "Florence Blanc-Renaud"
						},
						"bug_when": "2021-12-14 19:04:38 +0000",
						"thetext": "Additional note: also reproducible on Fedora 36, with the following packages:\n# rpm -qa 389-ds-base selinux-policy\n389-ds-base-2.0.11-1.fc36.x86_64\nselinux-policy-35.7-1.fc36.noarch"
					},
					{
						"isprivate": "0",
						"commentid": "15776648",
						"comment_count": "2",
						"who": {
							"text": "zpytela",
							"name": "Zdenek Pytela"
						},
						"bug_when": "2021-12-14 19:36:57 +0000",
						"thetext": "Florence,\n\nWe need to label /dev/shm/slapd-IPA-TEST and have a transition. Do you know which service creates this directory?"
					},
					{
						"isprivate": "0",
						"commentid": "15779469",
						"comment_count": "3",
						"who": {
							"text": "frenaud",
							"name": "Florence Blanc-Renaud"
						},
						"bug_when": "2021-12-15 14:57:02 +0000",
						"thetext": "Hi Zdenek,\n\nthe directory /dev/shm/slapd-IPA-TEST is created when ipa-restore is run, during the step that calls\n/usr/sbin/dsctl IPA-TEST ldif2db userRoot /var/lib/dirsrv/slapd-IPA-TEST/ldif/IPA-TEST-userRoot.ldif\n\nIf you need more details re. the internals of dsctl command, maybe @tbordaz@redhat.com can help"
					},
					{
						"isprivate": "0",
						"commentid": "15814435",
						"comment_count": "5",
						"who": {
							"text": "zpytela",
							"name": "Zdenek Pytela"
						},
						"bug_when": "2022-01-05 19:25:40 +0000",
						"thetext": "> F35 389-ds-base-2.0.11-1.fc35.x86_64\n> (https://koji.fedoraproject.org/koji/buildinfo?buildID=1858720) contains the\n> fix that moves the DB home under /dev/shm\n> (https://github.com/389ds/389-ds-base/issues/2790).\n> \n> The fix sets db_home_dir=/dev/shm/slapd-instance in\n> /usr/share/dirsrv/inf/defaults.inf. This properties file is used by the\n> command 'dscreate' when creating the instance.\n> My understanding is that selinux in F35 requires similar fix that was done\n> in selinux-policy-34.1.19-1.el9.\n> \n\nNeither dscreate or dsctl commands are SELinux confined:\n-rwxr-xr-x. 1 root root system_u:object_r:bin_t:s0 3647 Dec 16 16:30 /usr/sbin/dscreate\n-rwxr-xr-x. 1 root root system_u:object_r:bin_t:s0 5604 Dec 16 16:30 /usr/sbin/dsctl\n\nand the directory name is unpredictable:\n\nf35# ls -lZa /dev/shm\ntotal 8\ndrwxrwxrwt.  4 root   root   system_u:object_r:tmpfs_t:s0             120 Jan  5 14:11 .\ndrwxr-xr-x. 20 root   root   system_u:object_r:device_t:s0           4040 Jan  5 10:27 ..\n-rw-------.  1 dirsrv dirsrv system_u:object_r:dirsrv_tmpfs_t:s0       32 Jan  5 14:10 sem.slapd-IPA-TEST.stats\ndrwx------.  2 dirsrv dirsrv unconfined_u:object_r:user_tmp_t:s0       60 Jan  5 14:10 slapd-IPA-TEST\n\nso labeling of the directory cannot be handled in selinux-policy. The other example though:\n\n> I use to run the following command to create an instance: \n> dscreate create-template | sed -e 's/;suffix =/suffix = dc=example,dc=com/'\n> -e 's/;sample_entries = no/sample_entries = yes/' -e 's/;create_suffix_entry\n> = False/create_suffix_entry = True/' -e 's/;root_password =\n> Directory_Manager_Password/root_password = password/' >/tmp/foo2; dscreate\n> from-file /tmp/foo2\n\nseems to work:\n\ndrwxrwxrwt.  4 root   root   system_u:object_r:tmpfs_t:s0             120 Jan  5 14:11 .\ndrwxr-xr-x. 20 root   root   system_u:object_r:device_t:s0           4040 Jan  5 10:27 ..\n-rw-------.  1 dirsrv dirsrv system_u:object_r:dirsrv_tmpfs_t:s0       32 Jan  5 14:11 sem.slapd-localhost.stats\ndrwxrwx---.  2 dirsrv dirsrv unconfined_u:object_r:dirsrv_tmpfs_t:s0  120 Jan  5 14:11 slapd-localhost\n\nsupposedly because it reports some relabeling:\n\nStarting installation ...\nValidate installation settings ...\nCreate file system structures ...\nCreate self-signed certificate database ...\nPerform SELinux labeling ...\nCreate database backend: dc=example,dc=com ...\nPerform post-installation tasks ...\nCompleted installation for instance: slapd-localhost\n\nIs it possible to run similar relabeling in dscreate, or use other means to fix SELinux labels on /dev/shm/slapd-NAME?\n\n\nf35# rpm -qa 389-ds-base freeipa-server selinux-policy\nselinux-policy-35.7-1.fc35.noarch\n389-ds-base-2.0.12-1.fc35.x86_64\nfreeipa-server-4.9.8-1.fc35.x86_64"
					},
					{
						"isprivate": "0",
						"commentid": "15815894",
						"comment_count": "6",
						"who": {
							"text": "tbordaz",
							"name": "thierry bordaz"
						},
						"bug_when": "2022-01-06 09:05:06 +0000",
						"thetext": "if the info file indicates that selinux is enabled (/usr/share/dirsrv/inf/defaults.inf:with_selinux), dscreate label (via selinux.restorecon(path, recursive=True)) a set of paths including '/dev/shm' (aka db_home_directory) (see https://github.com/389ds/389-ds-base/blob/master/src/lib389/lib389/instance/setup.py#L911).\nAlthough we can relabel it in some commands like dsctl I think it would be a kind of workaround.\n\nif ipa-server-install labeled /dev/shm, then ipa-server-install -uninstall removed /dev/shm/slapd-IPA-TEST. Upon restore /dev/shm/slapd-IPA-TEST is recreated but is missing the label. Is that the scenario you are thinking of ?"
					},
					{
						"isprivate": "0",
						"commentid": "15815927",
						"comment_count": "7",
						"who": {
							"text": "zpytela",
							"name": "Zdenek Pytela"
						},
						"bug_when": "2022-01-06 09:20:16 +0000",
						"thetext": "(In reply to thierry bordaz from comment #6)\n> if the info file indicates that selinux is enabled\n> (/usr/share/dirsrv/inf/defaults.inf:with_selinux), dscreate label (via\n> selinux.restorecon(path, recursive=True)) a set of paths including\n> '/dev/shm' (aka db_home_directory) (see\n> https://github.com/389ds/389-ds-base/blob/master/src/lib389/lib389/instance/\n> setup.py#L911).\n> Although we can relabel it in some commands like dsctl I think it would be a\n> kind of workaround.\n> \n> if ipa-server-install labeled /dev/shm, then ipa-server-install -uninstall\n> removed /dev/shm/slapd-IPA-TEST. Upon restore /dev/shm/slapd-IPA-TEST is\n> recreated but is missing the label. Is that the scenario you are thinking of\n> ?\n\nIf /dev/shm/.* is created by a service which runs a confined executable, it can be and actually is handled in selinux-policy.\nFor a cli command we cannot do it, so I can think of 2 solutions - run restorecon in ipa-restore or have some parts of the task, which restore /dev/shm, as a systemd service, too."
					},
					{
						"isprivate": "0",
						"commentid": "15831149",
						"comment_count": "8",
						"who": {
							"text": "frenaud",
							"name": "Florence Blanc-Renaud"
						},
						"bug_when": "2022-01-11 10:21:40 +0000",
						"thetext": "Moving to 389-ds-base component as agreed with tbordaz"
					},
					{
						"isprivate": "0",
						"commentid": "15831900",
						"comment_count": "9",
						"who": {
							"text": "mreynolds"
						},
						"bug_when": "2022-01-11 14:22:11 +0000",
						"thetext": "This was supposed to be fixed in this selinux-policy bug:\n\nhttps://bugzilla.redhat.com/show_bug.cgi?id=1843238\n\nWith this change this feature was working correctly so I'm surprised to see if popping up again.\n\nDoes this need to backported to Fedora zpytela?"
					},
					{
						"isprivate": "0",
						"commentid": "15832300",
						"comment_count": "10",
						"who": {
							"text": "mreynolds"
						},
						"bug_when": "2022-01-11 16:13:12 +0000",
						"thetext": "(In reply to mreynolds from comment #9)\n> This was supposed to be fixed in this selinux-policy bug:\n> \n> https://bugzilla.redhat.com/show_bug.cgi?id=1843238\n> \n> With this change this feature was working correctly so I'm surprised to see\n> if popping up again.\n> \n> Does this need to backported to Fedora zpytela?\n\nSorry was a bit hasty in my reply, this is only happening after a IPA backup/restore (not standard server install).  Investigating, but I will need to know more about IPA's backup/restore process..."
					},
					{
						"isprivate": "0",
						"commentid": "15832432",
						"comment_count": "11",
						"who": {
							"text": "frenaud",
							"name": "Florence Blanc-Renaud"
						},
						"bug_when": "2022-01-11 16:43:21 +0000",
						"thetext": "Hi Mark,\nthe code of ipa-backup is available here: https://pagure.io/freeipa/blob/master/f/ipaserver/install/ipa_backup.py\nIt mainly does commands equivalent to \"dsctl <instance> db2ldif --replication <backend> ldiffile\" (once for the domain backend, once for ipaca backend), then \"dsctl <instance> db2bak backupdir\".\n\nThe code of ipa-restore is available here: https://pagure.io/freeipa/blob/master/f/ipaserver/install/ipa_restore.py\nIt uses the files created by ipa-backup and calls \"dsctl <instance> ldif2db <backend> ldiffile\". This is the step that creates the /dev/shm/slapd-IPA-TEST.\n\nLater ipa-restore calls \"ipactl start\" and the step starting 389-ds fails because it can't read /dev/shm/slapd-IPA-TEST/DBVERSION."
					},
					{
						"isprivate": "0",
						"commentid": "15832477",
						"comment_count": "12",
						"who": {
							"text": "mreynolds"
						},
						"bug_when": "2022-01-11 17:02:12 +0000",
						"thetext": "(In reply to Florence Blanc-Renaud from comment #11)\n> Hi Mark,\n> the code of ipa-backup is available here:\n> https://pagure.io/freeipa/blob/master/f/ipaserver/install/ipa_backup.py\n> It mainly does commands equivalent to \"dsctl <instance> db2ldif\n> --replication <backend> ldiffile\" (once for the domain backend, once for\n> ipaca backend), then \"dsctl <instance> db2bak backupdir\".\n> \n> The code of ipa-restore is available here:\n> https://pagure.io/freeipa/blob/master/f/ipaserver/install/ipa_restore.py\n> It uses the files created by ipa-backup and calls \"dsctl <instance> ldif2db\n> <backend> ldiffile\". This is the step that creates the\n> /dev/shm/slapd-IPA-TEST.\n\nIs IPA always calling \"dsctl INSTANCE bak2db\"?  If it is then we can fix it in our script (dsctl).  However, if IPA is manually doing the restore (meaning IPA is copying the files over itself) then DS can NOT fix this and IPA will need to do the restorecon itself.  Looking at the IPA source it does look like IPA is calling bak2db, but I don't know if it always calls \"dsctl bak2db\".  I will assume it is, but if there are cases where it is manually done by IPA then we will have problems."
					},
					{
						"isprivate": "0",
						"commentid": "15837086",
						"comment_count": "13",
						"who": {
							"text": "zpytela",
							"name": "Zdenek Pytela"
						},
						"bug_when": "2022-01-12 14:02:50 +0000",
						"thetext": "(In reply to mreynolds from comment #10)\n> (In reply to mreynolds from comment #9)\n> > This was supposed to be fixed in this selinux-policy bug:\n> > \n> > https://bugzilla.redhat.com/show_bug.cgi?id=1843238\n> > \n> > With this change this feature was working correctly so I'm surprised to see\n> > if popping up again.\n> > \n> > Does this need to backported to Fedora zpytela?\n> \n> Sorry was a bit hasty in my reply, this is only happening after a IPA\n> backup/restore (not standard server install).  Investigating, but I will\n> need to know more about IPA's backup/restore process...\n\nThis time it is a different issue. Anyway almost always Fedora contains a superset of rules of RHEL.\n\nNote so far we have managed to find 3 possible solutions:\n- run restorecon after files restoring and before ipactl start\n- include SELinux context or all extended attributes in both backup and restore\n- handle restoring as a systemd service"
					},
					{
						"isprivate": "0",
						"commentid": "15837278",
						"comment_count": "14",
						"who": {
							"text": "mreynolds"
						},
						"bug_when": "2022-01-12 14:41:34 +0000",
						"thetext": "(In reply to Florence Blanc-Renaud from comment #11)\n> Hi Mark,\n> the code of ipa-backup is available here:\n> https://pagure.io/freeipa/blob/master/f/ipaserver/install/ipa_backup.py\n> It mainly does commands equivalent to \"dsctl <instance> db2ldif\n> --replication <backend> ldiffile\" (once for the domain backend, once for\n> ipaca backend), then \"dsctl <instance> db2bak backupdir\".\n> \n> The code of ipa-restore is available here:\n> https://pagure.io/freeipa/blob/master/f/ipaserver/install/ipa_restore.py\n> It uses the files created by ipa-backup and calls \"dsctl <instance> ldif2db\n> <backend> ldiffile\". This is the step that creates the\n> /dev/shm/slapd-IPA-TEST.\n> \n> Later ipa-restore calls \"ipactl start\" and the step starting 389-ds fails\n> because it can't read /dev/shm/slapd-IPA-TEST/DBVERSION.\n\n\nI can not reproduce this with a standalone DS instance.\n\nThis is what I tried, did I miss a step?\n\n# getenforce\nEnforcing\n\n# dsctl slapd-localhost stop\n# dsctl slapd-localhost db2bak\n-->  copy backup to /tmp\n\n# dsctl slapd-localhost db2ldif userroot\n--> copy LDIF to /tmp\n\n# dsctl slapd-localhost remove --do-it\n# dscreate from-file /data/dssetup.inf\n# dsctl slapd-localhost stop\n--> copy /tmp LDIF and bak to the proper locations under /var/lib/dirsrv/slapd-localhost/bak|ldif   Need to do this since the instance was removed and recreated\n\n# dsctl slapd-localhost bak2db <path to bakup>\n# dsctl slapd-localhost ldif2db userroot <path to ldif>\n# dsctl slapd-localhost start\n# ldapmodify ... ... succeeds\n\nThere are no errors and I can update database after starting it.  Did I do something wrong?"
					},
					{
						"isprivate": "0",
						"commentid": "15841462",
						"comment_count": "15",
						"who": {
							"text": "rcritten",
							"name": "Rob Crittenden"
						},
						"bug_when": "2022-01-13 17:16:13 +0000",
						"thetext": "I reproduced this manually using the provided tests.\n\nI'm not sure the root cause. I'm thinking that `dsctl ldif2db` doesn't set the contexts and perhaps dscreate does.\n\nTo test this theory I used ipa-restore to restore the data. The result was:\n\n# ls -lRZ /dev/shm\n/dev/shm:\ntotal 0\ndrwx------. 2 dirsrv dirsrv unconfined_u:object_r:user_tmp_t:s0 120 Jan 13 16:49 slapd-EXAMPLE-TEST\n\n/dev/shm/slapd-EXAMPLE-TEST:\ntotal 220444\n-rw-------. 1 dirsrv dirsrv system_u:object_r:user_tmp_t:s0      47874048 Jan 13 16:49 __db.001\n-rw-------. 1 dirsrv dirsrv system_u:object_r:user_tmp_t:s0      16179200 Jan 13 16:49 __db.002\n-rw-------. 1 dirsrv dirsrv system_u:object_r:user_tmp_t:s0     161677312 Jan 13 16:50 __db.003\n-rw-------. 1 dirsrv dirsrv unconfined_u:object_r:user_tmp_t:s0        51 Jan 13 16:49 DBVERSION\n\nThis reproduces the failing test.\n\nI used restorecon -R /dev/shm to fix the contexts. They were assigned as expected, so the policy I guess knows what things should be? Curious that they aren't created with the correct policy.\n\n# ls -lRZ /dev/shm\n/dev/shm:\ntotal 0\ndrwx------. 2 dirsrv dirsrv unconfined_u:object_r:dirsrv_tmpfs_t:s0 120 Jan 13 16:49 slapd-EXAMPLE-TEST\n\n/dev/shm/slapd-EXAMPLE-TEST:\ntotal 220444\n-rw-------. 1 dirsrv dirsrv system_u:object_r:dirsrv_tmpfs_t:s0      47874048 Jan 13 16:51 __db.001\n-rw-------. 1 dirsrv dirsrv system_u:object_r:dirsrv_tmpfs_t:s0      16179200 Jan 13 16:49 __db.002\n-rw-------. 1 dirsrv dirsrv system_u:object_r:dirsrv_tmpfs_t:s0     161677312 Jan 13 16:50 __db.003\n-rw-------. 1 dirsrv dirsrv unconfined_u:object_r:dirsrv_tmpfs_t:s0        51 Jan 13 16:49 DBVERSION\n\nI also tried re-running `dsctl ldif2db` and the contexts remained the same, reinforcing that it doesn't seem to be purposely changing them.\n\nSo my best guess is that either the context relies on the existence of the instance directory or dscreate is fixing the context as part of its configuration.\n\nI also tested the reproducer with a slight twist, replacing an existing IPA installation with one from backup:\n\n1. enable updates-testing, install freeipa-server packages\n2. ipa-server-install --domain ipa.test --realm IPA.TEST -a $PASSWORD -p $PASSWORD -U\n3. ipa-backup\n4. ipa-server-install --uninstall -U\n5. ipa-server-install <same options as step 2>\n6. ipa-restore /path/to/backup/from/step/3\n\nIn this case the contexts on /dev/shm are correct, probably because the /dev/shm instance exists already with the right SELinux context."
					},
					{
						"isprivate": "0",
						"commentid": "15841779",
						"comment_count": "16",
						"who": {
							"text": "mreynolds"
						},
						"bug_when": "2022-01-13 19:18:55 +0000",
						"thetext": "dscreate does call restorecon, and we can make dsctl bak2db call it as well.  My issue is that I need to reproduce this outside of IPA so our own QE team can verify it.  Did I miss a step in comment 14 ?"
					},
					{
						"isprivate": "0",
						"commentid": "15841805",
						"comment_count": "17",
						"who": {
							"text": "rcritten",
							"name": "Rob Crittenden"
						},
						"bug_when": "2022-01-13 19:27:29 +0000",
						"thetext": "I think the equivalent would be removing /dev/shm/* before calling db2ldif."
					},
					{
						"isprivate": "0",
						"commentid": "15841916",
						"comment_count": "18",
						"who": {
							"text": "mreynolds"
						},
						"bug_when": "2022-01-13 20:29:56 +0000",
						"thetext": "(In reply to Rob Crittenden from comment #17)\n> I think the equivalent would be removing /dev/shm/* before calling db2ldif.\n\nOk so \"IPA restore\" is restoring an entire instance FS layout via a tarball.  Meaning there is no underlying DS instance to begin with.  So dscreate is never used, it just does this untarring and then bak2db and ldif2db are called?\n\nAlso why do a bak2db, and then an ldif import?  Seems redundant."
					},
					{
						"isprivate": "0",
						"commentid": "15841996",
						"comment_count": "19",
						"who": {
							"text": "rcritten",
							"name": "Rob Crittenden"
						},
						"bug_when": "2022-01-13 21:01:44 +0000",
						"thetext": "Prior to doing the restore the stored LDIF is re-parsed and any RUV data is stripped out of it. Doing a full restore in IPA requires a database reset on any other replicated servers."
					},
					{
						"isprivate": "0",
						"commentid": "15855468",
						"comment_count": "22",
						"who": {
							"text": "mreynolds"
						},
						"bug_when": "2022-01-18 18:01:46 +0000",
						"thetext": "Rob, could you test this DS fedora copr build (f34/35):\n\nhttps://copr.fedorainfracloud.org/coprs/build/3196603\n\nIt has a fix in dsctl that will attempt to relabel the db-home-dir (/dev/shm/slapd-INST) after a successful bak2db."
					},
					{
						"isprivate": "0",
						"commentid": "15855571",
						"comment_count": "23",
						"who": {
							"text": "mreynolds"
						},
						"bug_when": "2022-01-18 18:39:51 +0000",
						"thetext": "Looks like I was able to reproduce this by deleting /dev/shm/slapd-INST before doing the bak2db:\n\n[18/Jan/2022:13:25:11.734193584 -0500] - ERR - bdb_version_write - Could not open file \"/dev/shm/slapd-localhost/DBVERSION\" for writing Netscape Portable Runtime -5966 (Access Denied.)\n[18/Jan/2022:13:25:11.739696008 -0500] - ERR - libdb - /dev/shm/slapd-localhost: Permission denied\n[18/Jan/2022:13:25:11.742553445 -0500] - CRIT - bdb_start - Opening database environment (/dev/shm/slapd-localhost) failed. err=13: Unexpected dbimpl error code\n[18/Jan/2022:13:25:11.748587854 -0500] - ERR - ldbm_back_start - Failed to init database, err=13 Unexpected dbimpl error code\n\n\nWith my test fix (copr build) it works in this scenario.  It would be nice to IAP to verify it before moving forward with the fix."
					},
					{
						"isprivate": "0",
						"commentid": "15856287",
						"comment_count": "24",
						"who": {
							"text": "mreynolds"
						},
						"bug_when": "2022-01-18 23:05:05 +0000",
						"thetext": "This COPR build below does a restorecon after a bak2db and ldif2db.  In my testing when I remove /dev/shm this build works and correctly updates /dev/shm/slapd-INSTANCE selinux label.  I was getting an almost identical failure as the IPA logs showed, and I was able to fix it.  However this build (fix in dsctl/python-lib389) in IPA tests shows that restorecon does NOT update the label of /dev/shm/slapd-INSTANCE.  I do not know enough about selinux to explain this behavior.  DS (ns-slapd) can not call restorecon itself because it runs as user \"dirsrv' and does not have permission to execute /usr/sbin/restorecon.  \n\nPerhaps IPA's restore script should run restorecon on /dev/shm ?  It would be worth testing at least, but I don't know what else we can do on the DS side.\n\nhttps://copr.fedorainfracloud.org/coprs/build/3196912"
					},
					{
						"isprivate": "0",
						"commentid": "15860261",
						"comment_count": "25",
						"who": {
							"text": "mreynolds"
						},
						"bug_when": "2022-01-19 17:53:58 +0000",
						"thetext": "The last thing DS can try is seeing if we can use systemd to call restorecon at server startup.  We will try this next..."
					},
					{
						"isprivate": "0",
						"commentid": "15860296",
						"comment_count": "26",
						"who": {
							"text": "abokovoy",
							"name": "Alexander Bokovoy"
						},
						"bug_when": "2022-01-19 18:11:40 +0000",
						"thetext": "you can use tmpfiles.d functionality to force relabeling:\n\n(from tmpfiles.d man page):\n\n       z\n           Adjust the access mode, user and group ownership, and restore the SELinux security context of a file or directory, if it exists. Lines of this type accept shell-style globs in place of normal path names. Does not follow symlinks.\n\n       Z\n           Recursively set the access mode, user and group ownership, and restore the SELinux security context of a file or directory if it exists, as well as of its subdirectories and the files contained therein (if applicable). Lines of this\n           type accept shell-style globs in place of normal path names. Does not follow symlinks.\n\n\nDefine a file and then use systemd-tmpfiles during dirsrv service startup? It might require running systemd-tmpfiles in a separate service file and depend on it."
					},
					{
						"isprivate": "0",
						"commentid": "15863830",
						"comment_count": "27",
						"who": {
							"text": "mreynolds"
						},
						"bug_when": "2022-01-20 15:41:56 +0000",
						"thetext": "(In reply to Alexander Bokovoy from comment #26)\n> you can use tmpfiles.d functionality to force relabeling:\n> \n> (from tmpfiles.d man page):\n> \n>        z\n>            Adjust the access mode, user and group ownership, and restore the\n> SELinux security context of a file or directory, if it exists. Lines of this\n> type accept shell-style globs in place of normal path names. Does not follow\n> symlinks.\n> \n>        Z\n>            Recursively set the access mode, user and group ownership, and\n> restore the SELinux security context of a file or directory if it exists, as\n> well as of its subdirectories and the files contained therein (if\n> applicable). Lines of this\n>            type accept shell-style globs in place of normal path names. Does\n> not follow symlinks.\n> \n> \n> Define a file and then use systemd-tmpfiles during dirsrv service startup?\n> It might require running systemd-tmpfiles in a separate service file and\n> depend on it.\n\nI don't know much about tmpfiles/systemd and trying update /etc/tmpfiles.d/dirsrv/slapd-localhost.conf does not update db_home_dir at server startup:\n\n[root@fedora retrocl]# cat /etc/tmpfiles.d/dirsrv-localhost.conf \nd /run/dirsrv 0770 dirsrv dirsrv\nd /run/lock/dirsrv/ 0770 dirsrv dirsrv\nd /run/lock/dirsrv/slapd-localhost 0770 dirsrv dirsrv\nz /dev/shm/slapd-localhost 0770 dirsrv dirsrv\nz /dev/shm/slapd-localhost/* 0600 dirsrv dirsrv\n\n\nI'll keep looking into this, but I might need help from someone more familiar with this stuff..."
					},
					{
						"isprivate": "0",
						"commentid": "15864495",
						"comment_count": "28",
						"who": {
							"text": "mreynolds"
						},
						"bug_when": "2022-01-20 18:51:08 +0000",
						"thetext": "Ok, I got this working using an ExecStartPre script in the service file.  I don't know if it will work in the IPA case, but I'll generate a new COPR test build..."
					},
					{
						"isprivate": "0",
						"commentid": "15867622",
						"comment_count": "29",
						"who": {
							"text": "mreynolds"
						},
						"bug_when": "2022-01-21 15:29:33 +0000",
						"thetext": "Upstream ticket:\n\nhttps://github.com/389ds/389-ds-base/issues/5127"
					},
					{
						"isprivate": "0",
						"commentid": "15874495",
						"comment_count": "33",
						"who": {
							"text": "mreynolds"
						},
						"bug_when": "2022-01-24 16:54:37 +0000",
						"thetext": "Fixed upstream:\n\nhttps://github.com/389ds/389-ds-base/issues/5127"
					},
					{
						"isprivate": "0",
						"commentid": "15875082",
						"comment_count": "34",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-01-24 19:51:56 +0000",
						"thetext": "FEDORA-2022-7f62add497 has been submitted as an update to Fedora 35. https://bodhi.fedoraproject.org/updates/FEDORA-2022-7f62add497"
					},
					{
						"isprivate": "0",
						"commentid": "15875961",
						"comment_count": "35",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-01-25 02:10:43 +0000",
						"thetext": "FEDORA-2022-7f62add497 has been pushed to the Fedora 35 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2022-7f62add497`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2022-7f62add497\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "15876697",
						"comment_count": "36",
						"who": {
							"text": "frenaud",
							"name": "Florence Blanc-Renaud"
						},
						"bug_when": "2022-01-25 08:32:03 +0000",
						"thetext": "Tested the bodhi update on fedora 35 (389-ds-base-2.0.13-1.fc35.x86_64), the backup/uninstall/restore scenario works well. I added karma to the bodhi update."
					},
					{
						"isprivate": "0",
						"commentid": "15920492",
						"comment_count": "37",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-02-04 01:22:28 +0000",
						"thetext": "FEDORA-2022-5aee32fbab has been pushed to the Fedora 35 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 2044429,
			"feedback": [
				{
					"bug_id": 2044429,
					"comment": {
						"id": 2359584,
						"karma": 1,
						"testcase_feedback": [
							{
								"comment_id": 2359584,
								"testcase": {
									"id": 142,
									"name": "QA:Testcase 389 ds base setup testcase"
								},
								"testcase_id": 142
							},
							{
								"comment_id": 2359584,
								"testcase": {
									"id": 143,
									"name": "QA:Testcase Create normalized dn cache testcase"
								},
								"testcase_id": 143
							},
							{
								"comment_id": 2359584,
								"testcase": {
									"id": 144,
									"name": "QA:Testcase Create normalized dn cache testcase2"
								},
								"testcase_id": 144
							}
						],
						"text": "Tested with ipa-backup/uninstall/ipa-restore, works well",
						"timestamp": "2022-01-25 16:18:42",
						"update_id": 369615,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/1cbca7b0643a627efade96d828034c6e658415d5bb72e57fc57e295efae8b689?s=24&d=retro",
							"email": "frenaud@redhat.com",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "gitfreeipa"
								}
							],
							"id": 3071,
							"name": "frenaud",
							"openid": "frenaud.id.fedoraproject.org"
						},
						"user_id": 3071
					},
					"comment_id": 2359584
				},
				{
					"bug_id": 2044429,
					"comment": {
						"id": 2382564,
						"karma": -1,
						"testcase_feedback": [
							{
								"comment_id": 2382564,
								"testcase": {
									"id": 142,
									"name": "QA:Testcase 389 ds base setup testcase"
								},
								"testcase_id": 142
							},
							{
								"comment_id": 2382564,
								"testcase": {
									"id": 143,
									"name": "QA:Testcase Create normalized dn cache testcase"
								},
								"testcase_id": 143
							},
							{
								"comment_id": 2382564,
								"testcase": {
									"id": 144,
									"name": "QA:Testcase Create normalized dn cache testcase2"
								},
								"testcase_id": 144
							}
						],
						"text": "So, couple things:\n\n* This was actually pushed stable successfully: it's [right there in the stable updates tree](https://dl.fedoraproject.org/pub/fedora/linux/updates/35/Everything/x86_64/Packages/3/). Bodhi got out of whack somehow.\n* This actually breaks FreeIPA upgrades and should not have been pushed stable at all. I'm investigating why ATM.",
						"timestamp": "2022-01-27 18:06:54",
						"update_id": 369615,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/0e6c01c694d74afb0cbb65bc1be91950111503818caf492c0938dc2b97c48c41?s=24&d=retro",
							"email": "awilliam@redhat.com",
							"groups": [
								{
									"name": "proventesters"
								},
								{
									"name": "provenpackager"
								},
								{
									"name": "packager"
								},
								{
									"name": "qa-tools-sig"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "news"
								},
								{
									"name": "gittriage"
								},
								{
									"name": "sysadmin"
								},
								{
									"name": "gitspin-kickstarts"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "gitgeneric-release"
								},
								{
									"name": "yak_farmers"
								},
								{
									"name": "triagers"
								},
								{
									"name": "qa"
								},
								{
									"name": "sysadmin-qa"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "gitmkinitrd"
								},
								{
									"name": "qa-admin"
								},
								{
									"name": "sysadmin-main"
								},
								{
									"name": "common-issues-triage"
								},
								{
									"name": "aws-qa"
								},
								{
									"name": "gitfedora-project-schedule"
								},
								{
									"name": "change-wranglers"
								},
								{
									"name": "fedora-ci-admins"
								},
								{
									"name": "program-management"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 302,
							"name": "adamwill",
							"openid": "adamwill.id.fedoraproject.org"
						},
						"user_id": 302
					},
					"comment_id": 2382564
				},
				{
					"bug_id": 2044429,
					"comment": {
						"id": 2383012,
						"testcase_feedback": [
							{
								"comment_id": 2383012,
								"testcase": {
									"id": 142,
									"name": "QA:Testcase 389 ds base setup testcase"
								},
								"testcase_id": 142
							},
							{
								"comment_id": 2383012,
								"testcase": {
									"id": 143,
									"name": "QA:Testcase Create normalized dn cache testcase"
								},
								"testcase_id": 143
							},
							{
								"comment_id": 2383012,
								"testcase": {
									"id": 144,
									"name": "QA:Testcase Create normalized dn cache testcase2"
								},
								"testcase_id": 144
							}
						],
						"text": "Cause of the problem turns out to be https://bugzilla.redhat.com/show_bug.cgi?id=2047323 , @mreynolds is getting that fixed now.",
						"timestamp": "2022-01-27 21:22:46",
						"update_id": 369615,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/0e6c01c694d74afb0cbb65bc1be91950111503818caf492c0938dc2b97c48c41?s=24&d=retro",
							"email": "awilliam@redhat.com",
							"groups": [
								{
									"name": "proventesters"
								},
								{
									"name": "provenpackager"
								},
								{
									"name": "packager"
								},
								{
									"name": "qa-tools-sig"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "news"
								},
								{
									"name": "gittriage"
								},
								{
									"name": "sysadmin"
								},
								{
									"name": "gitspin-kickstarts"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "gitgeneric-release"
								},
								{
									"name": "yak_farmers"
								},
								{
									"name": "triagers"
								},
								{
									"name": "qa"
								},
								{
									"name": "sysadmin-qa"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "gitmkinitrd"
								},
								{
									"name": "qa-admin"
								},
								{
									"name": "sysadmin-main"
								},
								{
									"name": "common-issues-triage"
								},
								{
									"name": "aws-qa"
								},
								{
									"name": "gitfedora-project-schedule"
								},
								{
									"name": "change-wranglers"
								},
								{
									"name": "fedora-ci-admins"
								},
								{
									"name": "program-management"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 302,
							"name": "adamwill",
							"openid": "adamwill.id.fedoraproject.org"
						},
						"user_id": 302
					},
					"comment_id": 2383012
				},
				{
					"bug_id": 2044429,
					"comment": {
						"id": 2392277,
						"karma": 1,
						"testcase_feedback": [
							{
								"comment_id": 2392277,
								"testcase": {
									"id": 142,
									"name": "QA:Testcase 389 ds base setup testcase"
								},
								"testcase_id": 142
							},
							{
								"comment_id": 2392277,
								"testcase": {
									"id": 143,
									"name": "QA:Testcase Create normalized dn cache testcase"
								},
								"testcase_id": 143
							},
							{
								"comment_id": 2392277,
								"testcase": {
									"id": 144,
									"name": "QA:Testcase Create normalized dn cache testcase2"
								},
								"testcase_id": 144
							}
						],
						"text": "The update properly fixes the winsync issue #[5079](https://github.com/389ds/389-ds-base/issues/5079), as can be seen in IPA's nightly PR #[1481](https://github.com/freeipa-pr-ci2/freeipa/pull/1481): [test report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/215eeb26-8433-11ec-b3e7-fa163e67bee2/report.html), using the following [packages](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/215eeb26-8433-11ec-b3e7-fa163e67bee2/installed_packages/installed_packages_master.log.gz): 389-ds-base-2.0.14-1.fc35.x86_64",
						"timestamp": "2022-02-03 19:42:07",
						"update_id": 374646,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/1cbca7b0643a627efade96d828034c6e658415d5bb72e57fc57e295efae8b689?s=24&d=retro",
							"email": "frenaud@redhat.com",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "gitfreeipa"
								}
							],
							"id": 3071,
							"name": "frenaud",
							"openid": "frenaud.id.fedoraproject.org"
						},
						"user_id": 3071
					},
					"comment_id": 2392277
				}
			],
			"parent": true,
			"security": true,
			"title": "CVE-2021-45720 lru: Use after free in lru crate",
			"bugzilla": {
				"bug_id": "2044429",
				"alias": "CVE-2021-45720",
				"creation_ts": "2022-01-24 15:29:13 +0000",
				"short_desc": "CVE-2021-45720 lru: Use after free in lru crate",
				"delta_ts": "2022-01-24 16:01:49 +0000",
				"bug_status": "CLOSED",
				"resolution": "UPSTREAM",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"2044430"
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "15874186",
						"comment_count": "0",
						"who": {
							"text": "psampaio",
							"name": "Pedro Sampaio"
						},
						"bug_when": "2022-01-24 15:29:13 +0000",
						"thetext": "An issue was discovered in the lru crate before 0.7.1 for Rust. The iterators have a use-after-free, as demonstrated by an access after a pop operation.\n\nhttps://raw.githubusercontent.com/rustsec/advisory-db/main/crates/lru/RUSTSEC-2021-0130.md\nhttps://rustsec.org/advisories/RUSTSEC-2021-0130.html"
					},
					{
						"isprivate": "0",
						"commentid": "15874191",
						"comment_count": "1",
						"who": {
							"text": "psampaio",
							"name": "Pedro Sampaio"
						},
						"bug_when": "2022-01-24 15:29:26 +0000",
						"thetext": "Created rust-lru-cache tracking bugs for this issue:\n\nAffects: fedora-all [bug 2044430]"
					},
					{
						"isprivate": "0",
						"commentid": "15874298",
						"comment_count": "2",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2022-01-24 16:01:48 +0000",
						"thetext": "This CVE Bugzilla entry is for community support informational purposes only as it does not affect a package in a commercially supported Red Hat product. Refer to the dependent bugs for status of those individual community products."
					}
				]
			}
		},
		{
			"bug_id": 2044430,
			"feedback": [
				{
					"bug_id": 2044430,
					"comment": {
						"id": 2359584,
						"karma": 1,
						"testcase_feedback": [
							{
								"comment_id": 2359584,
								"testcase": {
									"id": 142,
									"name": "QA:Testcase 389 ds base setup testcase"
								},
								"testcase_id": 142
							},
							{
								"comment_id": 2359584,
								"testcase": {
									"id": 143,
									"name": "QA:Testcase Create normalized dn cache testcase"
								},
								"testcase_id": 143
							},
							{
								"comment_id": 2359584,
								"testcase": {
									"id": 144,
									"name": "QA:Testcase Create normalized dn cache testcase2"
								},
								"testcase_id": 144
							}
						],
						"text": "Tested with ipa-backup/uninstall/ipa-restore, works well",
						"timestamp": "2022-01-25 16:18:42",
						"update_id": 369615,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/1cbca7b0643a627efade96d828034c6e658415d5bb72e57fc57e295efae8b689?s=24&d=retro",
							"email": "frenaud@redhat.com",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "gitfreeipa"
								}
							],
							"id": 3071,
							"name": "frenaud",
							"openid": "frenaud.id.fedoraproject.org"
						},
						"user_id": 3071
					},
					"comment_id": 2359584
				},
				{
					"bug_id": 2044430,
					"comment": {
						"id": 2382564,
						"karma": -1,
						"testcase_feedback": [
							{
								"comment_id": 2382564,
								"testcase": {
									"id": 142,
									"name": "QA:Testcase 389 ds base setup testcase"
								},
								"testcase_id": 142
							},
							{
								"comment_id": 2382564,
								"testcase": {
									"id": 143,
									"name": "QA:Testcase Create normalized dn cache testcase"
								},
								"testcase_id": 143
							},
							{
								"comment_id": 2382564,
								"testcase": {
									"id": 144,
									"name": "QA:Testcase Create normalized dn cache testcase2"
								},
								"testcase_id": 144
							}
						],
						"text": "So, couple things:\n\n* This was actually pushed stable successfully: it's [right there in the stable updates tree](https://dl.fedoraproject.org/pub/fedora/linux/updates/35/Everything/x86_64/Packages/3/). Bodhi got out of whack somehow.\n* This actually breaks FreeIPA upgrades and should not have been pushed stable at all. I'm investigating why ATM.",
						"timestamp": "2022-01-27 18:06:54",
						"update_id": 369615,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/0e6c01c694d74afb0cbb65bc1be91950111503818caf492c0938dc2b97c48c41?s=24&d=retro",
							"email": "awilliam@redhat.com",
							"groups": [
								{
									"name": "proventesters"
								},
								{
									"name": "provenpackager"
								},
								{
									"name": "packager"
								},
								{
									"name": "qa-tools-sig"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "news"
								},
								{
									"name": "gittriage"
								},
								{
									"name": "sysadmin"
								},
								{
									"name": "gitspin-kickstarts"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "gitgeneric-release"
								},
								{
									"name": "yak_farmers"
								},
								{
									"name": "triagers"
								},
								{
									"name": "qa"
								},
								{
									"name": "sysadmin-qa"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "gitmkinitrd"
								},
								{
									"name": "qa-admin"
								},
								{
									"name": "sysadmin-main"
								},
								{
									"name": "common-issues-triage"
								},
								{
									"name": "aws-qa"
								},
								{
									"name": "gitfedora-project-schedule"
								},
								{
									"name": "change-wranglers"
								},
								{
									"name": "fedora-ci-admins"
								},
								{
									"name": "program-management"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 302,
							"name": "adamwill",
							"openid": "adamwill.id.fedoraproject.org"
						},
						"user_id": 302
					},
					"comment_id": 2382564
				},
				{
					"bug_id": 2044430,
					"comment": {
						"id": 2383012,
						"testcase_feedback": [
							{
								"comment_id": 2383012,
								"testcase": {
									"id": 142,
									"name": "QA:Testcase 389 ds base setup testcase"
								},
								"testcase_id": 142
							},
							{
								"comment_id": 2383012,
								"testcase": {
									"id": 143,
									"name": "QA:Testcase Create normalized dn cache testcase"
								},
								"testcase_id": 143
							},
							{
								"comment_id": 2383012,
								"testcase": {
									"id": 144,
									"name": "QA:Testcase Create normalized dn cache testcase2"
								},
								"testcase_id": 144
							}
						],
						"text": "Cause of the problem turns out to be https://bugzilla.redhat.com/show_bug.cgi?id=2047323 , @mreynolds is getting that fixed now.",
						"timestamp": "2022-01-27 21:22:46",
						"update_id": 369615,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/0e6c01c694d74afb0cbb65bc1be91950111503818caf492c0938dc2b97c48c41?s=24&d=retro",
							"email": "awilliam@redhat.com",
							"groups": [
								{
									"name": "proventesters"
								},
								{
									"name": "provenpackager"
								},
								{
									"name": "packager"
								},
								{
									"name": "qa-tools-sig"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "news"
								},
								{
									"name": "gittriage"
								},
								{
									"name": "sysadmin"
								},
								{
									"name": "gitspin-kickstarts"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "gitgeneric-release"
								},
								{
									"name": "yak_farmers"
								},
								{
									"name": "triagers"
								},
								{
									"name": "qa"
								},
								{
									"name": "sysadmin-qa"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "gitmkinitrd"
								},
								{
									"name": "qa-admin"
								},
								{
									"name": "sysadmin-main"
								},
								{
									"name": "common-issues-triage"
								},
								{
									"name": "aws-qa"
								},
								{
									"name": "gitfedora-project-schedule"
								},
								{
									"name": "change-wranglers"
								},
								{
									"name": "fedora-ci-admins"
								},
								{
									"name": "program-management"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 302,
							"name": "adamwill",
							"openid": "adamwill.id.fedoraproject.org"
						},
						"user_id": 302
					},
					"comment_id": 2383012
				},
				{
					"bug_id": 2044430,
					"comment": {
						"id": 2392277,
						"karma": 1,
						"testcase_feedback": [
							{
								"comment_id": 2392277,
								"testcase": {
									"id": 142,
									"name": "QA:Testcase 389 ds base setup testcase"
								},
								"testcase_id": 142
							},
							{
								"comment_id": 2392277,
								"testcase": {
									"id": 143,
									"name": "QA:Testcase Create normalized dn cache testcase"
								},
								"testcase_id": 143
							},
							{
								"comment_id": 2392277,
								"testcase": {
									"id": 144,
									"name": "QA:Testcase Create normalized dn cache testcase2"
								},
								"testcase_id": 144
							}
						],
						"text": "The update properly fixes the winsync issue #[5079](https://github.com/389ds/389-ds-base/issues/5079), as can be seen in IPA's nightly PR #[1481](https://github.com/freeipa-pr-ci2/freeipa/pull/1481): [test report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/215eeb26-8433-11ec-b3e7-fa163e67bee2/report.html), using the following [packages](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/215eeb26-8433-11ec-b3e7-fa163e67bee2/installed_packages/installed_packages_master.log.gz): 389-ds-base-2.0.14-1.fc35.x86_64",
						"timestamp": "2022-02-03 19:42:07",
						"update_id": 374646,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/1cbca7b0643a627efade96d828034c6e658415d5bb72e57fc57e295efae8b689?s=24&d=retro",
							"email": "frenaud@redhat.com",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "gitfreeipa"
								}
							],
							"id": 3071,
							"name": "frenaud",
							"openid": "frenaud.id.fedoraproject.org"
						},
						"user_id": 3071
					},
					"comment_id": 2392277
				}
			],
			"security": true,
			"title": "CVE-2021-45720 389-ds-base: bundled lru: Use after free in lru crate [fedora-all]",
			"bugzilla": {
				"bug_id": "2044430",
				"creation_ts": "2022-01-24 15:29:18 +0000",
				"short_desc": "CVE-2021-45720 389-ds-base: bundled lru: Use after free in lru crate [fedora-all]",
				"delta_ts": "2022-03-11 13:14:38 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "2044429",
						"alias": "CVE-2021-45720",
						"creation_ts": "2022-01-24 15:29:13 +0000",
						"short_desc": "CVE-2021-45720 lru: Use after free in lru crate",
						"delta_ts": "2022-01-24 16:01:49 +0000",
						"bug_status": "CLOSED",
						"resolution": "UPSTREAM",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"2044430"
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "15874186",
								"comment_count": "0",
								"who": {
									"text": "psampaio",
									"name": "Pedro Sampaio"
								},
								"bug_when": "2022-01-24 15:29:13 +0000",
								"thetext": "An issue was discovered in the lru crate before 0.7.1 for Rust. The iterators have a use-after-free, as demonstrated by an access after a pop operation.\n\nhttps://raw.githubusercontent.com/rustsec/advisory-db/main/crates/lru/RUSTSEC-2021-0130.md\nhttps://rustsec.org/advisories/RUSTSEC-2021-0130.html"
							},
							{
								"isprivate": "0",
								"commentid": "15874191",
								"comment_count": "1",
								"who": {
									"text": "psampaio",
									"name": "Pedro Sampaio"
								},
								"bug_when": "2022-01-24 15:29:26 +0000",
								"thetext": "Created rust-lru-cache tracking bugs for this issue:\n\nAffects: fedora-all [bug 2044430]"
							},
							{
								"isprivate": "0",
								"commentid": "15874298",
								"comment_count": "2",
								"who": {
									"text": "prodsec-dev",
									"name": "Product Security DevOps Team"
								},
								"bug_when": "2022-01-24 16:01:48 +0000",
								"thetext": "This CVE Bugzilla entry is for community support informational purposes only as it does not affect a package in a commercially supported Red Hat product. Refer to the dependent bugs for status of those individual community products."
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "15874188",
						"comment_count": "0",
						"who": {
							"text": "psampaio",
							"name": "Pedro Sampaio"
						},
						"bug_when": "2022-01-24 15:29:18 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "15874189",
						"comment_count": "1",
						"who": {
							"text": "psampaio",
							"name": "Pedro Sampaio"
						},
						"bug_when": "2022-01-24 15:29:20 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=2044429,2044430\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "15874330",
						"comment_count": "2",
						"who": {
							"text": "decathorpe",
							"name": "Fabio Valentini"
						},
						"bug_when": "2022-01-24 16:12:32 +0000",
						"thetext": "The \"lru\" crate is not packaged for Fedora.\nHowever, a vulnerable version (0.6.6) is bundled in 389-ds-base."
					},
					{
						"isprivate": "0",
						"commentid": "15874364",
						"comment_count": "3",
						"who": {
							"text": "mreynolds"
						},
						"bug_when": "2022-01-24 16:22:44 +0000",
						"thetext": "Tests how we can upgrade lru to a newer version:\n\nlru v0.6.6 -> v0.7.2\n\nWill work on new builds shortly..."
					},
					{
						"isprivate": "0",
						"commentid": "15875067",
						"comment_count": "4",
						"who": {
							"text": "mreynolds"
						},
						"bug_when": "2022-01-24 19:44:29 +0000",
						"thetext": "Fixed upstream via: https://github.com/389ds/389-ds-base/issues/5132"
					},
					{
						"isprivate": "0",
						"commentid": "15875083",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-01-24 19:52:00 +0000",
						"thetext": "FEDORA-2022-7f62add497 has been submitted as an update to Fedora 35. https://bodhi.fedoraproject.org/updates/FEDORA-2022-7f62add497"
					},
					{
						"isprivate": "0",
						"commentid": "15875962",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-01-25 02:10:46 +0000",
						"thetext": "FEDORA-2022-7f62add497 has been pushed to the Fedora 35 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2022-7f62add497`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2022-7f62add497\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "15920494",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-02-04 01:22:31 +0000",
						"thetext": "FEDORA-2022-5aee32fbab has been pushed to the Fedora 35 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 2047323,
			"feedback": [
				{
					"bug_id": 2047323,
					"comment": {
						"id": 2392277,
						"karma": 1,
						"testcase_feedback": [
							{
								"comment_id": 2392277,
								"testcase": {
									"id": 142,
									"name": "QA:Testcase 389 ds base setup testcase"
								},
								"testcase_id": 142
							},
							{
								"comment_id": 2392277,
								"testcase": {
									"id": 143,
									"name": "QA:Testcase Create normalized dn cache testcase"
								},
								"testcase_id": 143
							},
							{
								"comment_id": 2392277,
								"testcase": {
									"id": 144,
									"name": "QA:Testcase Create normalized dn cache testcase2"
								},
								"testcase_id": 144
							}
						],
						"text": "The update properly fixes the winsync issue #[5079](https://github.com/389ds/389-ds-base/issues/5079), as can be seen in IPA's nightly PR #[1481](https://github.com/freeipa-pr-ci2/freeipa/pull/1481): [test report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/215eeb26-8433-11ec-b3e7-fa163e67bee2/report.html), using the following [packages](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/215eeb26-8433-11ec-b3e7-fa163e67bee2/installed_packages/installed_packages_master.log.gz): 389-ds-base-2.0.14-1.fc35.x86_64",
						"timestamp": "2022-02-03 19:42:07",
						"update_id": 374646,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/1cbca7b0643a627efade96d828034c6e658415d5bb72e57fc57e295efae8b689?s=24&d=retro",
							"email": "frenaud@redhat.com",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "gitfreeipa"
								}
							],
							"id": 3071,
							"name": "frenaud",
							"openid": "frenaud.id.fedoraproject.org"
						},
						"user_id": 3071
					},
					"comment_id": 2392277
				}
			],
			"title": "389-ds does not start: restorecon: lstat(/dev/shm/slapd-IPA-FARNZ-ORG-UK) failed",
			"bugzilla": {
				"bug_id": "2047323",
				"creation_ts": "2022-01-27 15:57:56 +0000",
				"short_desc": "389-ds does not start: restorecon: lstat(/dev/shm/slapd-IPA-FARNZ-ORG-UK) failed",
				"delta_ts": "2022-02-04 01:22:35 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"priority": "unspecified",
				"bug_severity": "unspecified",
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "15891922",
						"comment_count": "0",
						"who": {
							"text": "simon",
							"name": "Simon Farnsworth"
						},
						"bug_when": "2022-01-27 15:57:56 +0000",
						"thetext": "Description of problem:\n\nAfter the update from 2.0.12 to 2.0.13 in the Fdora 35 channel, 389-ds will not start, complaining:\n\nJan 27 15:52:28 homeserv.farnz.org.uk ds_selinux_restorecon.sh[3553]: restorecon: lstat(/dev/shm/slapd-IPA-FARNZ-ORG-UK) failed: No such file or directory\n\n\nVersion-Release number of selected component (if applicable):\n\n2.0.13\n\nHow reproducible:\n\nAll the time\n\nSteps to Reproduce:\n1. systemctl start dirsrv@IPA-FARNZ-ORG-UK\n\nActual results:\n\nFails to start. journalctl -xeu dirsrv@IPA-FARNZ-ORG-UK.service shows:\n\nJan 27 15:52:28 homeserv.farnz.org.uk systemd[1]: Starting 389 Directory Server IPA-FARNZ-ORG-UK....\n░░ Subject: A start job for unit dirsrv@IPA-FARNZ-ORG-UK.service has begun execution\n░░ Defined-By: systemd\n░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel\n░░ \n░░ A start job for unit dirsrv@IPA-FARNZ-ORG-UK.service has begun execution.\n░░ \n░░ The job identifier is 4524.\nJan 27 15:52:28 homeserv.farnz.org.uk ds_selinux_restorecon.sh[3553]: restorecon: lstat(/dev/shm/slapd-IPA-FARNZ-ORG-UK) failed: No such file or directory\nJan 27 15:52:28 homeserv.farnz.org.uk systemd[1]: dirsrv@IPA-FARNZ-ORG-UK.service: Control process exited, code=exited, status=255/EXCEPTION\n░░ Subject: Unit process exited\n░░ Defined-By: systemd\n░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel\n░░ \n░░ An ExecStartPre= process belonging to unit dirsrv@IPA-FARNZ-ORG-UK.service has exited.\n░░ \n░░ The process' exit code is 'exited' and its exit status is 255.\nJan 27 15:52:28 homeserv.farnz.org.uk systemd[1]: dirsrv@IPA-FARNZ-ORG-UK.service: Failed with result 'exit-code'.\n░░ Subject: Unit failed\n░░ Defined-By: systemd\n░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel\n░░ \n░░ The unit dirsrv@IPA-FARNZ-ORG-UK.service has entered the 'failed' state with result 'exit-code'.\nJan 27 15:52:28 homeserv.farnz.org.uk systemd[1]: Failed to start 389 Directory Server IPA-FARNZ-ORG-UK..\n░░ Subject: A start job for unit dirsrv@IPA-FARNZ-ORG-UK.service has failed\n░░ Defined-By: systemd\n░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel\n░░ \n░░ A start job for unit dirsrv@IPA-FARNZ-ORG-UK.service has finished with a failure.\n░░ \n░░ The job identifier is 4524 and the job result is failed.\n\n\nExpected results:\n\n389-ds to start and run\n\nAdditional info:\nIf I hack /usr/libexec/dirsrv/ds_selinux_restorecon.sh to have || true on the end of the restorecon line, everything works again. ipactl restart gets my full FreeIPA stack back up and running. I'm thus not blocked."
					},
					{
						"isprivate": "0",
						"commentid": "15893097",
						"comment_count": "1",
						"who": {
							"text": "awilliam",
							"name": "Adam Williamson"
						},
						"bug_when": "2022-01-27 20:35:45 +0000",
						"thetext": "Thanks! We're getting this fixed:\nhttps://github.com/389ds/389-ds-base/pull/5141"
					},
					{
						"isprivate": "0",
						"commentid": "15893326",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-01-27 21:57:52 +0000",
						"thetext": "FEDORA-2022-5aee32fbab has been submitted as an update to Fedora 35. https://bodhi.fedoraproject.org/updates/FEDORA-2022-5aee32fbab"
					},
					{
						"isprivate": "0",
						"commentid": "15920497",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-02-04 01:22:35 +0000",
						"thetext": "FEDORA-2022-5aee32fbab has been pushed to the Fedora 35 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "389-ds-base-2.0.14-1.fc35",
			"release_id": 51,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "389-ds-base-libs-debuginfo",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "aarch64"
					},
					{
						"name": "389-ds-base-debugsource",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "aarch64"
					},
					{
						"name": "389-ds-base-debuginfo",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "aarch64"
					},
					{
						"name": "389-ds-base",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "aarch64"
					},
					{
						"name": "389-ds-base-libs",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "aarch64"
					},
					{
						"name": "389-ds-base-devel",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "aarch64"
					},
					{
						"name": "389-ds-base-snmp",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "aarch64"
					},
					{
						"name": "389-ds-base-snmp-debuginfo",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "aarch64"
					}
				],
				"armv7hl": [
					{
						"name": "389-ds-base-debugsource",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "armv7hl"
					},
					{
						"name": "389-ds-base-libs-debuginfo",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "armv7hl"
					},
					{
						"name": "389-ds-base-debuginfo",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "armv7hl"
					},
					{
						"name": "389-ds-base",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "armv7hl"
					},
					{
						"name": "389-ds-base-libs",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "armv7hl"
					},
					{
						"name": "389-ds-base-devel",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "armv7hl"
					},
					{
						"name": "389-ds-base-snmp-debuginfo",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "armv7hl"
					},
					{
						"name": "389-ds-base-snmp",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "armv7hl"
					}
				],
				"noarch": [
					{
						"name": "cockpit-389-ds",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "noarch"
					},
					{
						"name": "python3-lib389",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "noarch"
					}
				],
				"ppc64le": [
					{
						"name": "389-ds-base-devel",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "ppc64le"
					},
					{
						"name": "389-ds-base-libs",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "ppc64le"
					},
					{
						"name": "389-ds-base-libs-debuginfo",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "ppc64le"
					},
					{
						"name": "389-ds-base-debuginfo",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "ppc64le"
					},
					{
						"name": "389-ds-base",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "ppc64le"
					},
					{
						"name": "389-ds-base-debugsource",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "ppc64le"
					},
					{
						"name": "389-ds-base-snmp",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "ppc64le"
					},
					{
						"name": "389-ds-base-snmp-debuginfo",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "389-ds-base-debuginfo",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "s390x"
					},
					{
						"name": "389-ds-base-debugsource",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "s390x"
					},
					{
						"name": "389-ds-base",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "s390x"
					},
					{
						"name": "389-ds-base-libs-debuginfo",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "s390x"
					},
					{
						"name": "389-ds-base-libs",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "s390x"
					},
					{
						"name": "389-ds-base-devel",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "s390x"
					},
					{
						"name": "389-ds-base-snmp-debuginfo",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "s390x"
					},
					{
						"name": "389-ds-base-snmp",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "389-ds-base",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "389-ds-base-debuginfo",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "x86_64"
					},
					{
						"name": "389-ds-base-libs-debuginfo",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "x86_64"
					},
					{
						"name": "389-ds-base-libs",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "x86_64"
					},
					{
						"name": "389-ds-base-debugsource",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "x86_64"
					},
					{
						"name": "389-ds-base",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "x86_64"
					},
					{
						"name": "389-ds-base-devel",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "x86_64"
					},
					{
						"name": "389-ds-base-snmp-debuginfo",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "x86_64"
					},
					{
						"name": "389-ds-base-snmp",
						"version": "2.0.14",
						"release": "1.fc35",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 2383056,
			"text": "This update has been submitted for testing by mreynolds. ",
			"timestamp": "2022-01-27 21:57:49",
			"update_id": 374646,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2383057,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2022-01-27 21:57:50",
			"update_id": 374646,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2383059,
			"text": "This update has obsoleted [389-ds-base-2.0.13-1.fc35](https://bodhi.fedoraproject.org/updates/FEDORA-2022-7f62add497), and has inherited its bugs and notes.",
			"timestamp": "2022-01-27 21:57:51",
			"update_id": 374646,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2384818,
			"text": "FEDORA-2022-5aee32fbab ejected from the push because \"Cannot find relevant tag for 389-ds-base-2.0.14-1.fc35.  None of ['f35-updates-testing', 'f35-updates-testing-pending'] are in ['epel9-next-testing-candidate', 'epel7-testing-candidate', 'dist-5E-epel-testing-candidate', 'f27-modular-updates-candidate', 'f34-container-updates-candidate', 'eln-updates-candidate', 'f30-modular-updates-candidate', 'f28-modular-updates-candidate', 'f28-container-updates-candidate', 'f30-container-updates-candidate', 'epel8-testing-candidate', 'f30-flatpak-updates-candidate', 'f35-container-updates-candidate', 'f32-modular-updates-candidate', 'f29-modular-updates-candidate', 'f29-container-updates-candidate', 'f29-flatpak-updates-candidate', 'f22-updates-candidate', 'f21-updates-candidate', 'f25-updates-candidate', 'f24-updates-candidate', 'f23-updates-candidate', 'f26-updates-candidate', 'f31-modular-updates-candidate', 'dist-6E-epel-testing-candidate', 'f32-flatpak-updates-candidate', 'f35-flatpak-updates-candidate', 'f27-updates-candidate', 'f28-updates-candidate', 'f30-updates-candidate', 'f29-updates-candidate', 'el8-modular-updates-candidate', 'f32-updates-candidate', 'epel9-testing-candidate', 'f31-updates-candidate', 'f31-container-updates-candidate', 'f31-flatpak-updates-candidate', 'f34-updates-candidate', 'f34-modular-updates-candidate', 'f34-flatpak-updates-candidate', 'f36-container-updates-candidate', 'f32-container-updates-candidate', 'epel8-next-testing-candidate', 'f35-updates-candidate', 'f35-modular-updates-candidate', 'f33-updates-candidate', 'f36-updates-candidate', 'f33-modular-updates-candidate', 'f33-container-updates-candidate', 'f33-flatpak-updates-candidate'].\"",
			"timestamp": "2022-01-29 01:55:11",
			"update_id": 374646,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2391905,
			"text": "This update has been submitted for testing by mreynolds. ",
			"timestamp": "2022-02-03 13:59:02",
			"update_id": 374646,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"bug_feedback": [
				{
					"bug": {
						"bug_id": 2027730,
						"title": "SELinux is preventing ns-slapd access to /dev/shm/slapd-IPA-TEST/DBVERSION"
					},
					"bug_id": 2027730,
					"comment_id": 2392277
				},
				{
					"bug": {
						"bug_id": 2044429,
						"parent": true,
						"security": true,
						"title": "CVE-2021-45720 lru: Use after free in lru crate"
					},
					"bug_id": 2044429,
					"comment_id": 2392277
				},
				{
					"bug": {
						"bug_id": 2044430,
						"security": true,
						"title": "CVE-2021-45720 389-ds-base: bundled lru: Use after free in lru crate [fedora-all]"
					},
					"bug_id": 2044430,
					"comment_id": 2392277
				},
				{
					"bug": {
						"bug_id": 2047323,
						"title": "389-ds does not start: restorecon: lstat(/dev/shm/slapd-IPA-FARNZ-ORG-UK) failed"
					},
					"bug_id": 2047323,
					"comment_id": 2392277
				}
			],
			"id": 2392277,
			"karma": 1,
			"testcase_feedback": [
				{
					"comment_id": 2392277,
					"testcase": {
						"id": 142,
						"name": "QA:Testcase 389 ds base setup testcase"
					},
					"testcase_id": 142
				},
				{
					"comment_id": 2392277,
					"testcase": {
						"id": 143,
						"name": "QA:Testcase Create normalized dn cache testcase"
					},
					"testcase_id": 143
				},
				{
					"comment_id": 2392277,
					"testcase": {
						"id": 144,
						"name": "QA:Testcase Create normalized dn cache testcase2"
					},
					"testcase_id": 144
				}
			],
			"text": "The update properly fixes the winsync issue #[5079](https://github.com/389ds/389-ds-base/issues/5079), as can be seen in IPA's nightly PR #[1481](https://github.com/freeipa-pr-ci2/freeipa/pull/1481): [test report](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/215eeb26-8433-11ec-b3e7-fa163e67bee2/report.html), using the following [packages](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/215eeb26-8433-11ec-b3e7-fa163e67bee2/installed_packages/installed_packages_master.log.gz): 389-ds-base-2.0.14-1.fc35.x86_64",
			"timestamp": "2022-02-03 19:42:07",
			"update_id": 374646,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/1cbca7b0643a627efade96d828034c6e658415d5bb72e57fc57e295efae8b689?s=24&d=retro",
				"email": "frenaud@redhat.com",
				"groups": [
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "gitfreeipa"
					}
				],
				"id": 3071,
				"name": "frenaud",
				"openid": "frenaud.id.fedoraproject.org"
			},
			"user_id": 3071
		},
		{
			"id": 2392278,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2022-02-03 19:42:08",
			"update_id": 374646,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2392915,
			"text": "This update has been pushed to stable.",
			"timestamp": "2022-02-04 01:23:20",
			"update_id": 374646,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2022-02-04 01:19:29",
	"date_stable": "2022-02-04 01:19:29",
	"date_submitted": "2022-01-27 21:57:49",
	"karma": 1,
	"meets_testing_requirements": true,
	"notes": "Bump version to 2.0.14-1\n\n----\n\nSecurity fix for CVE-2021-45720",
	"pushed": true,
	"release": {
		"branch": "f35",
		"candidate_tag": "f35-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f35",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 35",
		"mail_template": "fedora_errata_template",
		"name": "F35",
		"override_tag": "f35-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f35-signing-pending",
		"pending_stable_tag": "f35-updates-pending",
		"pending_testing_tag": "f35-updates-testing-pending",
		"stable_tag": "f35-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f35-updates-testing",
		"version": "35"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "unspecified",
	"stable_days": 7,
	"stable_karma": 1,
	"status": "stable",
	"suggest": "unspecified",
	"test_cases": [
		{
			"id": 142,
			"name": "QA:Testcase 389 ds base setup testcase"
		},
		{
			"id": 143,
			"name": "QA:Testcase Create normalized dn cache testcase"
		},
		{
			"id": 144,
			"name": "QA:Testcase Create normalized dn cache testcase2"
		}
	],
	"test_gating_status": "ignored",
	"title": "389-ds-base-2.0.14-1.fc35",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2022-5aee32fbab",
	"unstable_karma": -1,
	"updateid": "FEDORA-2022-5aee32fbab",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/91c229394c868a53f7014d94442b38fd77a2e060a07eeaa6c0d562c86b25c24e?s=24&d=retro",
		"email": "mreynolds@redhat.com",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "git389"
			},
			{
				"name": "git389test"
			},
			{
				"name": "gitrest389"
			},
			{
				"name": "pagure_contributor"
			}
		],
		"id": 1553,
		"name": "mreynolds",
		"openid": "mreynolds.id.fedoraproject.org"
	},
	"version_hash": "2ba9293d137c6e99e08436492d6dc3e93bd06304"
}
