{
	"alias": "FEDORA-2025-e4c104502d",
	"autotime": true,
	"bugs": [
		{
			"bug_id": 2343278,
			"security": true,
			"title": "CVE-2025-0938 python3.9: URL parser allowed square brackets in domain names [fedora-all]",
			"bugzilla": {
				"bug_id": "2343278",
				"creation_ts": "2025-01-31 20:54:46 +0000",
				"short_desc": "CVE-2025-0938 python3.9: URL parser allowed square brackets in domain names [fedora-all]",
				"delta_ts": "2025-02-12 02:56:23 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "2343237",
						"alias": "CVE-2025-0938",
						"creation_ts": "2025-01-31 18:01:10 +0000",
						"short_desc": "CVE-2025-0938 python: cpython: URL parser allowed square brackets in domain names",
						"delta_ts": "2025-02-03 17:02:30 +0000",
						"bug_status": "NEW",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"2343277",
							"2343279",
							"2343272",
							"2343273",
							"2343274",
							"2343275",
							"2343276",
							"2343278"
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "18354042",
								"comment_count": "0",
								"who": {
									"text": "bzimport",
									"name": "OSIDB Bzimport"
								},
								"bug_when": "2025-01-31 18:01:10 +0000",
								"thetext": "The Python standard library functions `urllib.parse.urlsplit` and `urlparse` accepted domain names that included square brackets which isn't valid according to RFC 3986. Square brackets are only meant to be used as delimiters for specifying IPv6 and IPvFuture hosts in URLs. This could result in differential parsing across the Python URL parser and other specification-compliant URL parsers."
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "18354178",
						"comment_count": "0",
						"who": {
							"text": "psampaio",
							"name": "Pedro Sampaio"
						},
						"bug_when": "2025-01-31 20:54:46 +0000",
						"thetext": "More information about this security flaw is available in the following bug:\n\nhttps://bugzilla.redhat.com/show_bug.cgi?id=2343237\n\nDisclaimer: Community trackers are created by Red Hat Product Security team on a best effort basis. Package maintainers are required to ascertain if the flaw indeed affects their package, before starting the update process."
					},
					{
						"isprivate": "0",
						"commentid": "18368977",
						"comment_count": "1",
						"who": {
							"text": "cstratak",
							"name": "Charalampos Stratakis"
						},
						"bug_when": "2025-02-10 23:05:25 +0000",
						"thetext": "PRs:\nhttps://src.fedoraproject.org/rpms/python3.9/pull-request/188\nhttps://src.fedoraproject.org/rpms/python3.9/pull-request/189\nhttps://src.fedoraproject.org/rpms/python3.9/pull-request/190\nhttps://src.fedoraproject.org/rpms/python3.9/pull-request/191"
					},
					{
						"isprivate": "0",
						"commentid": "18370017",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2025-02-11 18:05:31 +0000",
						"thetext": "FEDORA-2025-e4c104502d (python3.9-3.9.21-4.fc42) has been submitted as an update to Fedora 42.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2025-e4c104502d"
					},
					{
						"isprivate": "0",
						"commentid": "18370018",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2025-02-11 18:05:41 +0000",
						"thetext": "FEDORA-2025-39a10a2c79 (python3.9-3.9.21-4.fc43) has been submitted as an update to Fedora 43.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2025-39a10a2c79"
					},
					{
						"isprivate": "0",
						"commentid": "18370021",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2025-02-11 18:07:40 +0000",
						"thetext": "FEDORA-2025-e4c104502d (python3.9-3.9.21-4.fc42) has been pushed to the Fedora 42 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18370022",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2025-02-11 18:10:39 +0000",
						"thetext": "FEDORA-2025-39a10a2c79 (python3.9-3.9.21-4.fc43) has been pushed to the Fedora 43 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18370247",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2025-02-11 21:39:25 +0000",
						"thetext": "FEDORA-2025-be080d5ed4 (python3.9-3.9.21-4.fc41) has been submitted as an update to Fedora 41.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2025-be080d5ed4"
					},
					{
						"isprivate": "0",
						"commentid": "18370248",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2025-02-11 21:39:58 +0000",
						"thetext": "FEDORA-2025-66c560fa22 (python3.9-3.9.21-4.fc40) has been submitted as an update to Fedora 40.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2025-66c560fa22"
					},
					{
						"isprivate": "0",
						"commentid": "18370522",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2025-02-12 02:28:15 +0000",
						"thetext": "FEDORA-2025-66c560fa22 has been pushed to the Fedora 40 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2025-66c560fa22`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2025-66c560fa22\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "18370550",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2025-02-12 02:56:23 +0000",
						"thetext": "FEDORA-2025-be080d5ed4 has been pushed to the Fedora 41 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2025-be080d5ed4`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2025-be080d5ed4\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python3.9-3.9.21-4.fc42",
			"release_id": 84,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "python3.9-debugsource",
						"version": "3.9.21",
						"release": "4.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.9-debuginfo",
						"version": "3.9.21",
						"release": "4.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.9",
						"version": "3.9.21",
						"release": "4.fc42",
						"arch": "aarch64"
					}
				],
				"i686": [
					{
						"name": "python3.9-debuginfo",
						"version": "3.9.21",
						"release": "4.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.9-debugsource",
						"version": "3.9.21",
						"release": "4.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.9",
						"version": "3.9.21",
						"release": "4.fc42",
						"arch": "i686"
					}
				],
				"ppc64le": [
					{
						"name": "python3.9-debugsource",
						"version": "3.9.21",
						"release": "4.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.9-debuginfo",
						"version": "3.9.21",
						"release": "4.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.9",
						"version": "3.9.21",
						"release": "4.fc42",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "python3.9-debugsource",
						"version": "3.9.21",
						"release": "4.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.9",
						"version": "3.9.21",
						"release": "4.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.9-debuginfo",
						"version": "3.9.21",
						"release": "4.fc42",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "python3.9",
						"version": "3.9.21",
						"release": "4.fc42",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "python3.9-debugsource",
						"version": "3.9.21",
						"release": "4.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.9-debuginfo",
						"version": "3.9.21",
						"release": "4.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.9",
						"version": "3.9.21",
						"release": "4.fc42",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 3954874,
			"text": "This update was automatically created",
			"timestamp": "2025-02-11 18:05:28",
			"update_id": 692565,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3954878,
			"text": "This update's test gating status has been changed to 'waiting'.",
			"timestamp": "2025-02-11 18:07:26",
			"update_id": 692565,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3954879,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2025-02-11 18:07:26",
			"update_id": 692565,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3954880,
			"text": "This update has been submitted for stable by bodhi",
			"timestamp": "2025-02-11 18:07:37",
			"update_id": 692565,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"critpath_groups": "",
	"date_approved": "2025-02-11 18:07:37",
	"date_pushed": "2025-02-11 18:07:37",
	"date_stable": "2025-02-11 18:07:37",
	"date_submitted": "2025-02-11 18:05:28",
	"date_testing": "2025-02-11 18:07:26",
	"meets_testing_requirements": true,
	"notes": "Automatic update for python3.9-3.9.21-4.fc42.\n\n##### **Changelog**\n\n```\n* Mon Feb 10 2025 Charalampos Stratakis <cstratak@redhat.com> - 3.9.21-4\n- Security fix for CVE-2025-0938\n- Fixes: rhbz#2343278\n\n```",
	"pushed": true,
	"release": {
		"branch": "f42",
		"candidate_tag": "f42-updates-candidate",
		"create_automatic_updates": true,
		"dist_tag": "f42",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 42",
		"mail_template": "fedora_errata_template",
		"name": "F42",
		"override_tag": "f42-override",
		"package_manager": "unspecified",
		"pending_signing_tag": "f42-signing-pending",
		"pending_stable_tag": "f42-updates-pending",
		"pending_testing_tag": "f42-updates-testing-pending",
		"stable_tag": "f42",
		"state": "pending",
		"testing_tag": "f42-updates-testing",
		"version": "42"
	},
	"severity": "unspecified",
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python3.9-3.9.21-4.fc42",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2025-e4c104502d",
	"unstable_karma": -3,
	"updateid": "FEDORA-2025-e4c104502d",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/af49eb5320c1c40d81a98d1fcdccc06c470c1458daab1a4f27be4cb170dbab3c?s=24&d=retro",
		"email": "cstratak@redhat.com",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "provenpackager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "modularity-wg"
			},
			{
				"name": "python-packagers-sig"
			}
		],
		"id": 2512,
		"name": "cstratak",
		"openid": "cstratak.id.fedoraproject.org"
	},
	"version_hash": "a70ddeef35a47ec9cb72ae0444857accda4c64d2"
}
