{
	"alias": "FEDORA-2023-d577604e6a",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 2196183,
			"parent": true,
			"security": true,
			"title": "CVE-2023-27043 python: Parsing errors in email/_parseaddr.py lead to incorrect value in email address part of tuple",
			"bugzilla": {
				"bug_id": "2196183",
				"alias": "CVE-2023-27043",
				"creation_ts": "2023-05-08 09:20:38 +0000",
				"short_desc": "CVE-2023-27043 python: Parsing errors in email/_parseaddr.py lead to incorrect value in email address part of tuple",
				"delta_ts": "2024-07-07 20:33:36 +0000",
				"bug_status": "NEW",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"2196184",
					"2196185",
					"2196186",
					"2196187",
					"2196188",
					"2196190",
					"2196191",
					"2196192",
					"2196193",
					"2196194",
					"2196200",
					"2196201",
					"2196202",
					"2196203",
					"2196204",
					"2196205",
					"2196206",
					"2196207",
					"2196208",
					"2196209",
					"2196210",
					"2196211",
					"2196212"
				],
				"blocked": [
					{
						"bug_id": "2193413",
						"error": "NotPermitted"
					}
				],
				"external_bugs": {
					"text": "RHSA-2024:3062",
					"name": "Red Hat Product Errata"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "17250049",
						"comment_count": "0",
						"who": {
							"text": "saroy",
							"name": "Sandipan Roy"
						},
						"bug_when": "2023-05-08 09:20:38 +0000",
						"thetext": "The e-mail module of Python 0 - 2.7.18, 3.x - 3.11 incorrectly parses e-mail addresses which contain a special character. This vulnerability allows attackers to send messages from e-ail addresses that would otherwise be rejected.\n\nhttps://github.com/python/cpython/issues/102988\nhttp://python.org"
					},
					{
						"isprivate": "0",
						"commentid": "17250082",
						"comment_count": "1",
						"who": {
							"text": "saroy",
							"name": "Sandipan Roy"
						},
						"bug_when": "2023-05-08 09:24:15 +0000",
						"thetext": "Created mingw-python3 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196185]\n\n\nCreated python2.7 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196186]\n\n\nCreated python3.10 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196187]\n\n\nCreated python3.11 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196188]\n\n\nCreated python3.12 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196190]\n\n\nCreated python3.6 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196191]\n\n\nCreated python3.7 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196192]\n\n\nCreated python3.8 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196193]\n\n\nCreated python3.9 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196194]\n\n\nCreated python34 tracking bugs for this issue:\n\nAffects: epel-7 [bug 2196184]"
					},
					{
						"isprivate": "0",
						"commentid": "17250084",
						"comment_count": "2",
						"who": {
							"text": "saroy",
							"name": "Sandipan Roy"
						},
						"bug_when": "2023-05-08 09:24:58 +0000",
						"thetext": "https://github.com/advisories/GHSA-5mwm-wccq-xqcp"
					},
					{
						"isprivate": "0",
						"commentid": "17649881",
						"comment_count": "9",
						"who": {
							"text": "lbalhar",
							"name": "Lum√≠r Balhar"
						},
						"bug_when": "2023-09-20 14:13:19 +0000",
						"thetext": "We have investigated the problem in the original patch that was reverted and proposed a solution. There is a new PR addressing this but it's progressing slowly. We are closely monitoring it. https://github.com/python/cpython/pull/108250\n\nThe previously merged and then reverted patch demonstrates that we should be very careful with fixes like this."
					},
					{
						"isprivate": "0",
						"commentid": "17816442",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-12-26 01:45:45 +0000",
						"thetext": "FEDORA-2023-87771f4249 has been pushed to the Fedora 39 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "17817624",
						"comment_count": "11",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-12-28 00:53:24 +0000",
						"thetext": "FEDORA-2023-c0bf8c0c4e has been pushed to the Fedora 38 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "17841518",
						"comment_count": "12",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2024-01-15 16:03:56 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:0256 https://access.redhat.com/errata/RHSA-2024:0256"
					},
					{
						"isprivate": "0",
						"commentid": "17856465",
						"comment_count": "13",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2024-01-24 16:31:00 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2024:0466 https://access.redhat.com/errata/RHSA-2024:0466"
					},
					{
						"isprivate": "0",
						"commentid": "17856541",
						"comment_count": "14",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2024-01-24 16:40:16 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9.2 Extended Update Support\n\nVia RHSA-2024:0454 https://access.redhat.com/errata/RHSA-2024:0454"
					},
					{
						"isprivate": "0",
						"commentid": "17856704",
						"comment_count": "15",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2024-01-24 16:49:37 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.6 Extended Update Support\n\nVia RHSA-2024:0430 https://access.redhat.com/errata/RHSA-2024:0430"
					},
					{
						"isprivate": "0",
						"commentid": "17867680",
						"comment_count": "16",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2024-01-30 13:25:12 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.8 Extended Update Support\n\nVia RHSA-2024:0586 https://access.redhat.com/errata/RHSA-2024:0586"
					},
					{
						"isprivate": "0",
						"commentid": "17993988",
						"comment_count": "19",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2024-04-30 10:02:00 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2024:2292 https://access.redhat.com/errata/RHSA-2024:2292"
					},
					{
						"isprivate": "0",
						"commentid": "18027377",
						"comment_count": "20",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2024-05-22 09:26:17 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:2985 https://access.redhat.com/errata/RHSA-2024:2985"
					},
					{
						"isprivate": "0",
						"commentid": "18027466",
						"comment_count": "21",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2024-05-22 09:43:02 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:3062 https://access.redhat.com/errata/RHSA-2024:3062"
					}
				]
			}
		},
		{
			"bug_id": 2196190,
			"security": true,
			"title": "CVE-2023-27043 python3.12: python: Parsing errors in email/_parseaddr.py lead to incorrect value in email address part of tuple [fedora-all]",
			"bugzilla": {
				"bug_id": "2196190",
				"creation_ts": "2023-05-08 09:23:31 +0000",
				"short_desc": "CVE-2023-27043 python3.12: python: Parsing errors in email/_parseaddr.py lead to incorrect value in email address part of tuple [fedora-all]",
				"delta_ts": "2023-12-28 00:53:27 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "2196183",
						"alias": "CVE-2023-27043",
						"creation_ts": "2023-05-08 09:20:38 +0000",
						"short_desc": "CVE-2023-27043 python: Parsing errors in email/_parseaddr.py lead to incorrect value in email address part of tuple",
						"delta_ts": "2024-07-07 20:33:36 +0000",
						"bug_status": "NEW",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"2196184",
							"2196185",
							"2196186",
							"2196187",
							"2196188",
							"2196190",
							"2196191",
							"2196192",
							"2196193",
							"2196194",
							"2196200",
							"2196201",
							"2196202",
							"2196203",
							"2196204",
							"2196205",
							"2196206",
							"2196207",
							"2196208",
							"2196209",
							"2196210",
							"2196211",
							"2196212"
						],
						"blocked": [
							{
								"bug_id": "2193413",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2024:3062",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "17250049",
								"comment_count": "0",
								"who": {
									"text": "saroy",
									"name": "Sandipan Roy"
								},
								"bug_when": "2023-05-08 09:20:38 +0000",
								"thetext": "The e-mail module of Python 0 - 2.7.18, 3.x - 3.11 incorrectly parses e-mail addresses which contain a special character. This vulnerability allows attackers to send messages from e-ail addresses that would otherwise be rejected.\n\nhttps://github.com/python/cpython/issues/102988\nhttp://python.org"
							},
							{
								"isprivate": "0",
								"commentid": "17250082",
								"comment_count": "1",
								"who": {
									"text": "saroy",
									"name": "Sandipan Roy"
								},
								"bug_when": "2023-05-08 09:24:15 +0000",
								"thetext": "Created mingw-python3 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196185]\n\n\nCreated python2.7 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196186]\n\n\nCreated python3.10 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196187]\n\n\nCreated python3.11 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196188]\n\n\nCreated python3.12 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196190]\n\n\nCreated python3.6 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196191]\n\n\nCreated python3.7 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196192]\n\n\nCreated python3.8 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196193]\n\n\nCreated python3.9 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2196194]\n\n\nCreated python34 tracking bugs for this issue:\n\nAffects: epel-7 [bug 2196184]"
							},
							{
								"isprivate": "0",
								"commentid": "17250084",
								"comment_count": "2",
								"who": {
									"text": "saroy",
									"name": "Sandipan Roy"
								},
								"bug_when": "2023-05-08 09:24:58 +0000",
								"thetext": "https://github.com/advisories/GHSA-5mwm-wccq-xqcp"
							},
							{
								"isprivate": "0",
								"commentid": "17649881",
								"comment_count": "9",
								"who": {
									"text": "lbalhar",
									"name": "Lum√≠r Balhar"
								},
								"bug_when": "2023-09-20 14:13:19 +0000",
								"thetext": "We have investigated the problem in the original patch that was reverted and proposed a solution. There is a new PR addressing this but it's progressing slowly. We are closely monitoring it. https://github.com/python/cpython/pull/108250\n\nThe previously merged and then reverted patch demonstrates that we should be very careful with fixes like this."
							},
							{
								"isprivate": "0",
								"commentid": "17816442",
								"comment_count": "10",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2023-12-26 01:45:45 +0000",
								"thetext": "FEDORA-2023-87771f4249 has been pushed to the Fedora 39 stable repository.\nIf problem still persists, please make note of it in this bug report."
							},
							{
								"isprivate": "0",
								"commentid": "17817624",
								"comment_count": "11",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2023-12-28 00:53:24 +0000",
								"thetext": "FEDORA-2023-c0bf8c0c4e has been pushed to the Fedora 38 stable repository.\nIf problem still persists, please make note of it in this bug report."
							},
							{
								"isprivate": "0",
								"commentid": "17841518",
								"comment_count": "12",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-01-15 16:03:56 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:0256 https://access.redhat.com/errata/RHSA-2024:0256"
							},
							{
								"isprivate": "0",
								"commentid": "17856465",
								"comment_count": "13",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-01-24 16:31:00 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2024:0466 https://access.redhat.com/errata/RHSA-2024:0466"
							},
							{
								"isprivate": "0",
								"commentid": "17856541",
								"comment_count": "14",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-01-24 16:40:16 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9.2 Extended Update Support\n\nVia RHSA-2024:0454 https://access.redhat.com/errata/RHSA-2024:0454"
							},
							{
								"isprivate": "0",
								"commentid": "17856704",
								"comment_count": "15",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-01-24 16:49:37 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.6 Extended Update Support\n\nVia RHSA-2024:0430 https://access.redhat.com/errata/RHSA-2024:0430"
							},
							{
								"isprivate": "0",
								"commentid": "17867680",
								"comment_count": "16",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-01-30 13:25:12 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.8 Extended Update Support\n\nVia RHSA-2024:0586 https://access.redhat.com/errata/RHSA-2024:0586"
							},
							{
								"isprivate": "0",
								"commentid": "17993988",
								"comment_count": "19",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-04-30 10:02:00 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2024:2292 https://access.redhat.com/errata/RHSA-2024:2292"
							},
							{
								"isprivate": "0",
								"commentid": "18027377",
								"comment_count": "20",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-05-22 09:26:17 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:2985 https://access.redhat.com/errata/RHSA-2024:2985"
							},
							{
								"isprivate": "0",
								"commentid": "18027466",
								"comment_count": "21",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-05-22 09:43:02 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:3062 https://access.redhat.com/errata/RHSA-2024:3062"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "17250070",
						"comment_count": "0",
						"who": {
							"text": "saroy",
							"name": "Sandipan Roy"
						},
						"bug_when": "2023-05-08 09:23:31 +0000",
						"thetext": "\nMore information about this security flaw is available in the following bug:\n\nhttp://bugzilla.redhat.com/show_bug.cgi?id=2196183\n\nDisclaimer: Community trackers are created by Red Hat Product Security team on a best effort basis. Package maintainers are required to ascertain if the flaw indeed affects their package, before starting the update process."
					},
					{
						"isprivate": "0",
						"commentid": "17250071",
						"comment_count": "1",
						"who": {
							"text": "saroy",
							"name": "Sandipan Roy"
						},
						"bug_when": "2023-05-08 09:23:34 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=2196183,2196190\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "17811090",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-12-19 10:29:24 +0000",
						"thetext": "FEDORA-2023-f3498cc9ee has been submitted as an update to Fedora 40. https://bodhi.fedoraproject.org/updates/FEDORA-2023-f3498cc9ee"
					},
					{
						"isprivate": "0",
						"commentid": "17811126",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-12-19 10:50:26 +0000",
						"thetext": "FEDORA-2023-d577604e6a has been submitted as an update to Fedora 39. https://bodhi.fedoraproject.org/updates/FEDORA-2023-d577604e6a"
					},
					{
						"isprivate": "0",
						"commentid": "17811179",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-12-19 11:45:34 +0000",
						"thetext": "FEDORA-2023-c0bf8c0c4e has been submitted as an update to Fedora 38. https://bodhi.fedoraproject.org/updates/FEDORA-2023-c0bf8c0c4e"
					},
					{
						"isprivate": "0",
						"commentid": "17811229",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-12-19 12:12:10 +0000",
						"thetext": "FEDORA-2023-f3498cc9ee has been pushed to the Fedora 40 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "17811829",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-12-20 01:08:19 +0000",
						"thetext": "FEDORA-2023-c0bf8c0c4e has been pushed to the Fedora 38 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2023-c0bf8c0c4e`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2023-c0bf8c0c4e\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "17811881",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-12-20 01:28:24 +0000",
						"thetext": "FEDORA-2023-d577604e6a has been pushed to the Fedora 39 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2023-d577604e6a`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2023-d577604e6a\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "17816931",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-12-27 01:29:57 +0000",
						"thetext": "FEDORA-2023-d577604e6a has been pushed to the Fedora 39 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "17817625",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-12-28 00:53:27 +0000",
						"thetext": "FEDORA-2023-c0bf8c0c4e has been pushed to the Fedora 38 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python3.12-3.12.1-2.fc39",
			"release_id": 70,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "python3.12-debugsource",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "aarch64"
					},
					{
						"name": "python3-devel",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "aarch64"
					},
					{
						"name": "python3-tkinter",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "aarch64"
					},
					{
						"name": "python3-idle",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "aarch64"
					},
					{
						"name": "python3-debug",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "aarch64"
					},
					{
						"name": "python3.12-debuginfo",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "aarch64"
					},
					{
						"name": "python3-libs",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "aarch64"
					},
					{
						"name": "python3-test",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "aarch64"
					},
					{
						"name": "python3",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "aarch64"
					}
				],
				"i686": [
					{
						"name": "python3.12-debugsource",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "i686"
					},
					{
						"name": "python3-libs",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "i686"
					},
					{
						"name": "python3-test",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "i686"
					},
					{
						"name": "python3.12-debuginfo",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "i686"
					},
					{
						"name": "python3-debug",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "i686"
					},
					{
						"name": "python3-idle",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "i686"
					},
					{
						"name": "python3-tkinter",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "i686"
					},
					{
						"name": "python3-devel",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "i686"
					},
					{
						"name": "python3",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "i686"
					}
				],
				"noarch": [
					{
						"name": "python-unversioned-command",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "noarch"
					}
				],
				"ppc64le": [
					{
						"name": "python3-tkinter",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "ppc64le"
					},
					{
						"name": "python3-devel",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "ppc64le"
					},
					{
						"name": "python3.12-debugsource",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "ppc64le"
					},
					{
						"name": "python3-idle",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "ppc64le"
					},
					{
						"name": "python3-debug",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "ppc64le"
					},
					{
						"name": "python3-test",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "ppc64le"
					},
					{
						"name": "python3-libs",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "ppc64le"
					},
					{
						"name": "python3.12-debuginfo",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "ppc64le"
					},
					{
						"name": "python3",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "python3-libs",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "s390x"
					},
					{
						"name": "python3-test",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "s390x"
					},
					{
						"name": "python3.12-debuginfo",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "s390x"
					},
					{
						"name": "python3.12-debugsource",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "s390x"
					},
					{
						"name": "python3-debug",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "s390x"
					},
					{
						"name": "python3-idle",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "s390x"
					},
					{
						"name": "python3-tkinter",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "s390x"
					},
					{
						"name": "python3-devel",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "s390x"
					},
					{
						"name": "python3",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "python3.12",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "python3-devel",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "x86_64"
					},
					{
						"name": "python3-idle",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "x86_64"
					},
					{
						"name": "python3-tkinter",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "x86_64"
					},
					{
						"name": "python3",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "x86_64"
					},
					{
						"name": "python3.12-debugsource",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "x86_64"
					},
					{
						"name": "python3-debug",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "x86_64"
					},
					{
						"name": "python3.12-debuginfo",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "x86_64"
					},
					{
						"name": "python3-test",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "x86_64"
					},
					{
						"name": "python3-libs",
						"version": "3.12.1",
						"release": "2.fc39",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 3326767,
			"text": "This update has been submitted for testing by churchyard. ",
			"timestamp": "2023-12-19 10:50:22",
			"update_id": 573148,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3326768,
			"text": "This update's test gating status has been changed to 'waiting'.",
			"timestamp": "2023-12-19 10:50:23",
			"update_id": 573148,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3326861,
			"text": "This update's test gating status has been changed to 'passed'.",
			"timestamp": "2023-12-19 12:25:02",
			"update_id": 573148,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3327500,
			"text": "This update has been pushed to testing.",
			"timestamp": "2023-12-20 01:29:17",
			"update_id": 573148,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3327546,
			"karma": 1,
			"text": "Works.",
			"timestamp": "2023-12-20 01:39:43",
			"update_id": 573148,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/1a8afd83231ef5ba905344806ba95b39f2abd77b399b0ee217ec3e6fa30a4825?s=24&d=retro",
				"email": "bojan@rexursive.com",
				"groups": [
					{
						"name": "packager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "trust admins"
					}
				],
				"id": 198,
				"name": "bojan",
				"openid": "bojan.id.fedoraproject.org"
			},
			"user_id": 198
		},
		{
			"id": 3328714,
			"karma": 1,
			"timestamp": "2023-12-21 03:14:38",
			"update_id": 573148,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/5545678c86b7a87ee5d907a87573978f63c78b2d498edda166dac72f81003f73?s=24&d=retro",
				"email": "geraldo.simiao.kutz@gmail.com",
				"groups": [
					{
						"name": "qa"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "ambassadors"
					},
					{
						"name": "fedora-br"
					},
					{
						"name": "advocates"
					},
					{
						"name": "respins-sig"
					}
				],
				"id": 5881,
				"name": "geraldosimiao",
				"openid": "geraldosimiao.id.fedoraproject.org"
			},
			"user_id": 5881
		},
		{
			"id": 3328722,
			"text": "This update can be pushed to stable now if the maintainer wishes",
			"timestamp": "2023-12-21 03:15:09",
			"update_id": 573148,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3329984,
			"karma": 1,
			"text": "works for me",
			"timestamp": "2023-12-22 02:59:33",
			"update_id": 573148,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/d826994e83ce867281f73d85986dd475938841874b75a83a82cdb184f6af8749?s=24&d=retro",
				"email": "rosset.filipe@gmail.com",
				"groups": [
					{
						"name": "proventesters"
					},
					{
						"name": "packager"
					},
					{
						"name": "provenpackager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "ambassadors"
					},
					{
						"name": "l10n"
					},
					{
						"name": "cvsl10n"
					},
					{
						"name": "fedora-br"
					},
					{
						"name": "trust admins"
					}
				],
				"id": 124,
				"name": "filiperosset",
				"openid": "filiperosset.id.fedoraproject.org"
			},
			"user_id": 124
		},
		{
			"id": 3330167,
			"karma": 1,
			"text": "works for me",
			"timestamp": "2023-12-22 07:09:48",
			"update_id": 573148,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/c626775cb5584b1a49ea4a5cabb248e54e49c09185ebbf4fbce72265255956f0?s=24&d=retro",
				"email": "mrunge@redhat.com",
				"groups": [
					{
						"name": "proventesters"
					},
					{
						"name": "provenpackager"
					},
					{
						"name": "packager"
					},
					{
						"name": "python-sig"
					},
					{
						"name": "centosproject-email-aliases"
					},
					{
						"name": "gitovirt"
					},
					{
						"name": "sig-cloud"
					},
					{
						"name": "ambassadors"
					},
					{
						"name": "gitnodejs-packaging"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "python-packagers-sig"
					},
					{
						"name": "sig-extras"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "sig-opstools"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "sig-messaging"
					},
					{
						"name": "openstack-sig"
					}
				],
				"id": 189,
				"name": "mrunge",
				"openid": "mrunge.id.fedoraproject.org"
			},
			"user_id": 189
		},
		{
			"id": 3331596,
			"karma": 1,
			"text": "Works well and fixes the vulnerability.",
			"timestamp": "2023-12-25 10:24:10",
			"update_id": 573148,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/43b68973106261bbbf2ac130b7c5d1c27fb91e2546b3e4a22dbcd5c50a3c681e?s=24&d=retro",
				"email": "lbalhar@redhat.com",
				"groups": [
					{
						"name": "packager"
					},
					{
						"name": "python-sig"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "realtime"
					},
					{
						"name": "machine-learning-sig"
					},
					{
						"name": "3d-printing-sig"
					},
					{
						"name": "python-packagers-sig"
					}
				],
				"id": 2936,
				"name": "lbalhar",
				"openid": "lbalhar.id.fedoraproject.org"
			},
			"user_id": 2936
		},
		{
			"id": 3332143,
			"karma": 1,
			"timestamp": "2023-12-26 20:01:28",
			"update_id": 573148,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/f80c96a3994c2479fc4815a146079bf93ade230fe3f3993213d2b8222cafc73d?s=24&d=retro",
				"email": "fzatlouk@redhat.com",
				"groups": [
					{
						"name": "packager"
					},
					{
						"name": "qa-tools-sig"
					},
					{
						"name": "provenpackager"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "qa-admin"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "sysadmin-qa"
					},
					{
						"name": "sysadmin"
					},
					{
						"name": "ambassadors"
					},
					{
						"name": "advocates"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "qa"
					},
					{
						"name": "ipausers"
					}
				],
				"id": 2240,
				"name": "frantisekz",
				"openid": "frantisekz.id.fedoraproject.org"
			},
			"user_id": 2240
		},
		{
			"id": 3332144,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2023-12-26 20:01:28",
			"update_id": 573148,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3332306,
			"text": "This update has been pushed to stable.",
			"timestamp": "2023-12-27 01:30:04",
			"update_id": 573148,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"critpath": true,
	"critpath_groups": "core critical-path-anaconda critical-path-apps critical-path-base critical-path-build critical-path-compose critical-path-deepin-desktop critical-path-gnome critical-path-kde critical-path-lxde critical-path-lxqt critical-path-server critical-path-standard critical-path-xfce",
	"date_approved": "2023-12-26 20:01:28",
	"date_pushed": "2023-12-27 01:28:52",
	"date_stable": "2023-12-27 01:28:52",
	"date_submitted": "2023-12-19 10:50:21",
	"date_testing": "2023-12-20 01:27:46",
	"karma": 6,
	"meets_testing_requirements": true,
	"notes": "Security fix for CVE-2023-27043",
	"pushed": true,
	"release": {
		"branch": "f39",
		"candidate_tag": "f39-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f39",
		"eol": "2024-11-26",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 39",
		"mail_template": "fedora_errata_template",
		"name": "F39",
		"override_tag": "f39-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f39-signing-pending",
		"pending_stable_tag": "f39-updates-pending",
		"pending_testing_tag": "f39-updates-testing-pending",
		"stable_tag": "f39-updates",
		"state": "current",
		"testing_repository": "updates-testing",
		"testing_tag": "f39-updates-testing",
		"version": "39"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "medium",
	"stable_days": 14,
	"stable_karma": 6,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "passed",
	"title": "python3.12-3.12.1-2.fc39",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2023-d577604e6a",
	"unstable_karma": -3,
	"updateid": "FEDORA-2023-d577604e6a",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/132a6c64fa9fbe9311973f5c5c6a70942b256d23d62be638718fe091076731cf?s=24&d=retro",
		"email": "mhroncok@redhat.com",
		"groups": [
			{
				"name": "provenpackager"
			},
			{
				"name": "packager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "3d-printing-sig"
			},
			{
				"name": "python-packagers-sig"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "sysadmin-badges"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "sysadmin"
			},
			{
				"name": "lua-packagers-sig"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "cvsadmin"
			},
			{
				"name": "ambassadors"
			},
			{
				"name": "packaging-committee"
			},
			{
				"name": "advocates"
			},
			{
				"name": "modularity-wg"
			},
			{
				"name": "trust admins"
			}
		],
		"id": 533,
		"name": "churchyard",
		"openid": "churchyard.id.fedoraproject.org"
	},
	"version_hash": "ae189c64473c0c7c2d50a69e595f3cd5edf9fd00"
}
