{
	"alias": "FEDORA-EPEL-2024-08d8c17c5d",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 2328747,
			"security": true,
			"title": "CVE-2024-53899 python-virtualenv: potential command injection via virtual environment activation scripts [epel-9]",
			"bugzilla": {
				"bug_id": "2328747",
				"creation_ts": "2024-11-25 18:51:12 +0000",
				"short_desc": "CVE-2024-53899 python-virtualenv: potential command injection via virtual environment activation scripts [epel-9]",
				"delta_ts": "2024-12-05 17:06:30 +0000",
				"bug_status": "MODIFIED",
				"keywords": "Security, SecurityTracking",
				"priority": "high",
				"bug_severity": "high",
				"blocked": [
					{
						"bug_id": "2328554",
						"alias": "CVE-2024-53899",
						"creation_ts": "2024-11-24 17:01:25 +0000",
						"short_desc": "CVE-2024-53899 virtualenv: potential command injection via virtual environment activation scripts",
						"delta_ts": "2024-11-26 11:24:32 +0000",
						"bug_status": "NEW",
						"keywords": "Security",
						"priority": "high",
						"bug_severity": "high",
						"depends_on": [
							"2328745",
							"2328746",
							"2328747",
							"2328744",
							"2328748",
							"2328749",
							"2328750"
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "18279078",
								"comment_count": "0",
								"who": {
									"text": "bzimport",
									"name": "OSIDB Bzimport"
								},
								"bug_when": "2024-11-24 17:01:25 +0000",
								"thetext": "virtualenv before 20.26.6 allows command injection through the activation scripts for a virtual environment. Magic template strings are not quoted correctly when replacing. NOTE: this is not the same as CVE-2024-9287."
							}
						]
					}
				],
				"external_bugs": {
					"text": "python-virtualenv/pull-request/122",
					"name": "Fedora Package Sources"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "18280512",
						"comment_count": "0",
						"who": {
							"text": "rgatica",
							"name": "Robb Gatica"
						},
						"bug_when": "2024-11-25 18:51:12 +0000",
						"thetext": "More information about this security flaw is available in the following bug:\n\nhttps://bugzilla.redhat.com/show_bug.cgi?id=2328554\n\nDisclaimer: Community trackers are created by Red Hat Product Security team on a best effort basis. Package maintainers are required to ascertain if the flaw indeed affects their package, before starting the update process."
					},
					{
						"isprivate": "0",
						"commentid": "18293928",
						"comment_count": "1",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-12-05 17:06:30 +0000",
						"thetext": "FEDORA-EPEL-2024-08d8c17c5d (python-virtualenv-20.21.1-14.el9) has been submitted as an update to Fedora EPEL 9.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2024-08d8c17c5d"
					}
				]
			}
		},
		{
			"bug_id": 2328956,
			"title": "virtualenv regression: virtualenv --seeder pip --python=python3.12 uses pip for Python 3.9 and fails",
			"bugzilla": {
				"bug_id": "2328956",
				"creation_ts": "2024-11-26 14:03:52 +0000",
				"short_desc": "virtualenv regression: virtualenv --seeder pip --python=python3.12 uses pip for Python 3.9 and fails",
				"delta_ts": "2024-12-05 17:06:33 +0000",
				"bug_status": "MODIFIED",
				"priority": "unspecified",
				"bug_severity": "unspecified",
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "18281488",
						"comment_count": "0",
						"who": {
							"text": "mhroncok",
							"name": "Miro Hronƒçok"
						},
						"bug_when": "2024-11-26 14:03:52 +0000",
						"thetext": "Since the fix for bz2272958 landed in EPEL 9, it is not possible to use `virtualenv --seeder pip --python=python3.12` as it fails with:\n\n$ virtualenv -vvvv --seeder pip --python=python3.12 venv\n...\n86 add seed packages via PipInvoke(download=False, pip=bundle) [INFO session:55]\n167 pip seed by running: /builddir/venv/bin/python -m pip -q install --only-binary :all: --disable-pip-version-check --no-index pip==23.2.1 --find-links /usr/share/python3.12-wheels env of {'SHELL': '/bin/bash', 'HISTCONTROL': 'ignoredups', 'HISTSIZE': '1000', 'HOSTNAME': '815503ada5e04dfd9391f4c02f5e0aa2', 'container_host_version_id': '41', 'PWD': '/builddir', 'LOGNAME': 'mockbuild', 'container': 'systemd-nspawn', 'HOME': '/builddir', 'LANG': 'C.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:', 'PROMPT_COMMAND': 'printf \"\\\\033]0;<mock-chroot>\\\\007\"', 'TERM': 'vt100', 'USER': 'mockbuild', 'NOTIFY_SOCKET': '/run/host/notify', 'SHLVL': '1', 'container_host_id': 'fedora', 'PS1': '<mock-chroot> \\\\s-\\\\v\\\\$ ', 'DEBUGINFOD_URLS': 'https://debuginfod.centos.org/ ', 'which_declare': 'declare -f', 'container_host_variant_id': 'xfce', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin', 'MAIL': '/var/spool/mail/mockbuild', 'container_uuid': 'cb2fba57-8768-4fdc-bda2-55c92f437ac2', 'OLDPWD': '/builddir', 'BASH_FUNC_which%%': '() {  ( alias;\\n eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@\\n}', '_': '/usr/bin/virtualenv', 'PLAT': 'linux-x86_64', 'PIP_USE_WHEEL': '1', 'PIP_USER': '0', 'PIP_NO_INPUT': '1', 'PYTHONPATH': '/usr/share/python3-wheels/pip-21.3.1-py3-none-any.whl'} [DEBUG pip_invoke:26]\nTraceback (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/usr/share/python3-wheels/pip-21.3.1-py3-none-any.whl/pip/__main__.py\", line 29, in <module>\n  File \"/usr/share/python3-wheels/pip-21.3.1-py3-none-any.whl/pip/_internal/cli/main.py\", line 9, in <module>\n  File \"/usr/share/python3-wheels/pip-21.3.1-py3-none-any.whl/pip/_internal/cli/autocompletion.py\", line 10, in <module>\n  File \"/usr/share/python3-wheels/pip-21.3.1-py3-none-any.whl/pip/_internal/cli/main_parser.py\", line 8, in <module>\n  File \"/usr/share/python3-wheels/pip-21.3.1-py3-none-any.whl/pip/_internal/cli/cmdoptions.py\", line 23, in <module>\n  File \"/usr/share/python3-wheels/pip-21.3.1-py3-none-any.whl/pip/_internal/cli/parser.py\", line 12, in <module>\n  File \"/usr/share/python3-wheels/pip-21.3.1-py3-none-any.whl/pip/_internal/configuration.py\", line 20, in <module>\n  File \"/usr/share/python3-wheels/pip-21.3.1-py3-none-any.whl/pip/_internal/exceptions.py\", line 7, in <module>\n  File \"/usr/share/python3-wheels/pip-21.3.1-py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py\", line 2164, in <module>\nAttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?\n371 RuntimeError: failed seed with code 1 [ERROR __main__:61]\n\n\n\nReverting https://src.fedoraproject.org/rpms/python-virtualenv/c/5cc394ff5c13e8c13289efee3428eff799de7e6a?branch=epel9 makes it work.\n\nApparently, the fix for --download with old Pythons broke --seeder pip for new Pythons :/"
					},
					{
						"isprivate": "0",
						"commentid": "18293929",
						"comment_count": "1",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-12-05 17:06:33 +0000",
						"thetext": "FEDORA-EPEL-2024-08d8c17c5d (python-virtualenv-20.21.1-14.el9) has been submitted as an update to Fedora EPEL 9.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2024-08d8c17c5d"
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python-virtualenv-20.21.1-14.el9",
			"release_id": 61,
			"signed": true,
			"type": "rpm",
			"package": {
				"noarch": [
					{
						"name": "python3-virtualenv",
						"version": "20.21.1",
						"release": "14.el9",
						"arch": "noarch"
					}
				],
				"src": [
					{
						"name": "python-virtualenv",
						"version": "20.21.1",
						"release": "14.el9",
						"arch": "src"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 3856080,
			"text": "This update has been submitted for testing by churchyard. ",
			"timestamp": "2024-12-05 17:06:27",
			"update_id": 674162,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3856081,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2024-12-05 17:06:28",
			"update_id": 674162,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"critpath_groups": "",
	"date_submitted": "2024-12-05 17:06:27",
	"notes": "- Security fix for CVE-2024-53899\n- Fix for `virtualenv --seeder pip --python=python3.12`",
	"release": {
		"branch": "epel9",
		"candidate_tag": "epel9-testing-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "epel9",
		"id_prefix": "FEDORA-EPEL",
		"long_name": "Fedora EPEL 9",
		"mail_template": "fedora_epel_legacy_errata_template",
		"name": "EPEL-9",
		"override_tag": "epel9-override",
		"package_manager": "unspecified",
		"pending_signing_tag": "epel9-signing-pending",
		"pending_stable_tag": "epel9-pending",
		"pending_testing_tag": "epel9-testing-pending",
		"stable_tag": "epel9",
		"state": "current",
		"testing_tag": "epel9-testing",
		"version": "9"
	},
	"request": "testing",
	"require_bugs": true,
	"require_testcases": true,
	"severity": "high",
	"stable_days": 7,
	"stable_karma": 2,
	"status": "pending",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python-virtualenv-20.21.1-14.el9",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2024-08d8c17c5d",
	"unstable_karma": -3,
	"updateid": "FEDORA-EPEL-2024-08d8c17c5d",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/e221b70024cf971d8b43de0260d2babde9179cdf72605bf3168420e3efe07423?s=24&d=retro",
		"email": "mhroncok@redhat.com",
		"groups": [
			{
				"name": "provenpackager"
			},
			{
				"name": "packager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "3d-printing-sig"
			},
			{
				"name": "python-packagers-sig"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "sysadmin-badges"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "sysadmin"
			},
			{
				"name": "lua-packagers-sig"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "cvsadmin"
			},
			{
				"name": "ambassadors"
			},
			{
				"name": "packaging-committee"
			},
			{
				"name": "advocates"
			}
		],
		"id": 533,
		"name": "churchyard",
		"openid": "churchyard.id.fedoraproject.org"
	},
	"version_hash": "7e5281394060087be1f4298004d195d690e97826"
}
