{
	"alias": "FEDORA-2023-690e150a39",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 2174018,
			"security": true,
			"title": "CVE-2023-24329 pypy: python: urllib.parse url blocklisting bypass [fedora-all]",
			"bugzilla": {
				"bug_id": "2174018",
				"creation_ts": "2023-02-28 16:59:01 +0000",
				"short_desc": "CVE-2023-24329 pypy: python: urllib.parse url blocklisting bypass [fedora-all]",
				"delta_ts": "2023-06-08 01:59:31 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "high",
				"bug_severity": "high",
				"blocked": [
					{
						"bug_id": "2173917",
						"alias": "CVE-2023-24329",
						"creation_ts": "2023-02-28 12:13:06 +0000",
						"short_desc": "CVE-2023-24329 python: urllib.parse url blocklisting bypass",
						"delta_ts": "2024-10-23 18:27:34 +0000",
						"bug_status": "NEW",
						"keywords": "Security",
						"priority": "high",
						"bug_severity": "high",
						"depends_on": [
							"2174009",
							"2174010",
							"2174011",
							"2174012",
							"2174013",
							"2174014",
							"2174015",
							"2174016",
							"2174017",
							"2174018",
							"2174019",
							"2174020",
							"2174024",
							"2174025",
							"2174026",
							"2174027",
							"2174028",
							"2174029",
							"2174030",
							"2174031",
							"2174032",
							"2174033",
							"2174034",
							"2174035",
							"2174036",
							"2174037",
							"2174038",
							"2174039",
							"2174040",
							"2174041",
							"2174042",
							"2174043",
							"2174044",
							"2174045",
							"2174046",
							"2174047",
							"2174048",
							"2174049",
							"2174050",
							"2174051",
							"2174052",
							"2174053",
							"2174054",
							"2174055",
							"2174056",
							"2174057",
							"2174058",
							"2174059",
							"2174060",
							"2174061",
							"2174062",
							"2174063",
							"2174064",
							"2174065",
							"2174066",
							"2174067",
							"2174068",
							"2174069",
							"2174070",
							"2174071",
							"2174072",
							"2174073",
							"2174074",
							"2174075",
							"2174076",
							"2174077",
							"2174078",
							"2174079",
							"2174080",
							"2174081",
							"2174082",
							"2174083",
							"2174084",
							"2174085",
							"2174086",
							"2174087",
							"2174088",
							"2174089",
							"2174090",
							"2174091",
							"2174092",
							"2174093",
							"2178009",
							"2210774",
							"2210775",
							"2210776",
							"2210777",
							"2210778",
							"2210779",
							"2210780",
							"2210781",
							"2210782",
							"2210783",
							"2210784",
							"2210785"
						],
						"blocked": [
							{
								"bug_id": "2171900",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2023:6793",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "17080580",
								"comment_count": "0",
								"who": {
									"text": "mrehak",
									"name": "Marian Rehak"
								},
								"bug_when": "2023-02-28 12:13:06 +0000",
								"thetext": "An issue in the urllib.parse component of Python before v3.11 allows attackers to bypass blocklisting methods by supplying a URL that starts with blank characters.\n\nhttps://pointernull.com/security/python-url-parse-problem.html\nhttps://github.com/python/cpython/pull/99421"
							},
							{
								"isprivate": "0",
								"commentid": "17081586",
								"comment_count": "1",
								"who": {
									"text": "mrehak",
									"name": "Marian Rehak"
								},
								"bug_when": "2023-02-28 16:59:28 +0000",
								"thetext": "Created mingw-python3 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2174012]\n\n\nCreated pypy tracking bugs for this issue:\n\nAffects: epel-7 [bug 2174017]\nAffects: fedora-all [bug 2174018]\n\n\nCreated pypy3.8 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2174019]\n\n\nCreated pypy3.9 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2174020]\n\n\nCreated python2.7 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2174011]\n\n\nCreated python3.10 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2174010]\n\n\nCreated python3.6 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2174013]\n\n\nCreated python3.7 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2174014]\n\n\nCreated python3.8 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2174015]\n\n\nCreated python3.9 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2174016]\n\n\nCreated python34 tracking bugs for this issue:\n\nAffects: epel-all [bug 2174009]"
							},
							{
								"isprivate": "0",
								"commentid": "17085966",
								"comment_count": "4",
								"who": {
									"text": "cstratak",
									"name": "Charalampos Stratakis"
								},
								"bug_when": "2023-03-02 01:43:12 +0000",
								"thetext": "There are still discussions upstream about the issue here: https://github.com/python/cpython/issues/102153"
							},
							{
								"isprivate": "0",
								"commentid": "17162949",
								"comment_count": "6",
								"who": {
									"text": "chmays",
									"name": "Chris Mays"
								},
								"bug_when": "2023-04-01 15:06:38 +0000",
								"thetext": "This bug is currently listed as being fixed in 3.11, however the link above (https://github.com/python/cpython/issues/102153) indicates that the alleged fix had zero affect.  Can/Should this be updated?"
							},
							{
								"isprivate": "0",
								"commentid": "17185906",
								"comment_count": "7",
								"who": {
									"text": "gabriele.gattari"
								},
								"bug_when": "2023-04-12 13:17:48 +0000",
								"thetext": "affects RHEL 8.7"
							},
							{
								"isprivate": "0",
								"commentid": "17190548",
								"comment_count": "8",
								"who": {
									"text": "lbalhar",
									"name": "Lumír Balhar"
								},
								"bug_when": "2023-04-14 10:26:25 +0000",
								"thetext": "I'm sorry it takes so long. There is no easy way out. The problem is very similar to the tarfile CVE (CVE-2007-4559). The behavior of urlparse and urlsplit functions is documented well and those functions are not intended to validate URLs. Therefore the upstream point of view is that the vulnerability is not in Python but might be in apps using these functions incorrectly.\n\nBecause the urllib module does not strictly follow any standard or RFC, it's almost impossible to do any backward-incompatible changes there.\n\nWe are trying to come up with a plan how to improve urllib module in Python in a way that would be future-proof, won't break backward compatibility, will be easily backportable into our systems and components and will be acceptable to upstream.\n\nI'm also gonna open a discussion with the product security team about the severity and our point of view."
							},
							{
								"isprivate": "0",
								"commentid": "17307334",
								"comment_count": "12",
								"who": {
									"text": "lbalhar",
									"name": "Lumír Balhar"
								},
								"bug_when": "2023-05-22 10:10:50 +0000",
								"thetext": "The fix is available in:\n\n3.12 (merged, will be part of the first beta release): https://github.com/python/cpython/commit/2f630e1ce18ad2e07428296532a68b11dc66ad10\n3.11 (merged, bugfix release 3.11.4 expected in June): https://github.com/python/cpython/commit/610cc0ab1b760b2abaac92bd256b96191c46b941\n3.10 (merged, security release 3.10.12 without date assigned): https://github.com/python/cpython/commit/f48a96a28012d28ae37a2f4587a780a5eb779946\n3.9: (WIP): https://github.com/python/cpython/pull/104593"
							},
							{
								"isprivate": "0",
								"commentid": "17376020",
								"comment_count": "17",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-08 11:52:43 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 6 Extended Lifecycle Support\n\nVia RHSA-2023:3550 https://access.redhat.com/errata/RHSA-2023:3550"
							},
							{
								"isprivate": "0",
								"commentid": "17377709",
								"comment_count": "18",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-09 07:57:37 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2023:3556 https://access.redhat.com/errata/RHSA-2023:3556"
							},
							{
								"isprivate": "0",
								"commentid": "17377710",
								"comment_count": "19",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-09 07:57:42 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2023:3555 https://access.redhat.com/errata/RHSA-2023:3555"
							},
							{
								"isprivate": "0",
								"commentid": "17388484",
								"comment_count": "20",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-14 08:42:19 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2023:3585 https://access.redhat.com/errata/RHSA-2023:3585"
							},
							{
								"isprivate": "0",
								"commentid": "17388561",
								"comment_count": "21",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-14 09:06:48 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2023:3591 https://access.redhat.com/errata/RHSA-2023:3591"
							},
							{
								"isprivate": "0",
								"commentid": "17388633",
								"comment_count": "22",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-14 09:46:53 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2023:3595 https://access.redhat.com/errata/RHSA-2023:3595"
							},
							{
								"isprivate": "0",
								"commentid": "17388646",
								"comment_count": "23",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-14 09:48:37 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2023:3594 https://access.redhat.com/errata/RHSA-2023:3594"
							},
							{
								"isprivate": "0",
								"commentid": "17407226",
								"comment_count": "24",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-22 11:47:12 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.6 Extended Update Support\n\nVia RHSA-2023:3776 https://access.redhat.com/errata/RHSA-2023:3776"
							},
							{
								"isprivate": "0",
								"commentid": "17407414",
								"comment_count": "25",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-22 12:57:02 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.2 Advanced Update Support\n  Red Hat Enterprise Linux 8.2 Update Services for SAP Solutions\n  Red Hat Enterprise Linux 8.2 Telecommunications Update Service\n\nVia RHSA-2023:3777 https://access.redhat.com/errata/RHSA-2023:3777"
							},
							{
								"isprivate": "0",
								"commentid": "17407646",
								"comment_count": "26",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-22 14:29:13 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2023:3780 https://access.redhat.com/errata/RHSA-2023:3780"
							},
							{
								"isprivate": "0",
								"commentid": "17407674",
								"comment_count": "27",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-22 14:39:13 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2023:3781 https://access.redhat.com/errata/RHSA-2023:3781"
							},
							{
								"isprivate": "0",
								"commentid": "17413269",
								"comment_count": "28",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-26 10:44:42 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.6 Extended Update Support\n\nVia RHSA-2023:3796 https://access.redhat.com/errata/RHSA-2023:3796"
							},
							{
								"isprivate": "0",
								"commentid": "17416052",
								"comment_count": "29",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-27 09:45:16 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.6 Extended Update Support\n\nVia RHSA-2023:3810 https://access.redhat.com/errata/RHSA-2023:3810"
							},
							{
								"isprivate": "0",
								"commentid": "17416076",
								"comment_count": "30",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-27 09:49:55 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2023:3811 https://access.redhat.com/errata/RHSA-2023:3811"
							},
							{
								"isprivate": "0",
								"commentid": "17422034",
								"comment_count": "31",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-29 11:34:24 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.4 Advanced Mission Critical Update Support\n  Red Hat Enterprise Linux 8.4 Update Services for SAP Solutions\n  Red Hat Enterprise Linux 8.4 Telecommunications Update Service\n\nVia RHSA-2023:3931 https://access.redhat.com/errata/RHSA-2023:3931"
							},
							{
								"isprivate": "0",
								"commentid": "17422102",
								"comment_count": "32",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-29 12:10:02 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.1 Update Services for SAP Solutions\n\nVia RHSA-2023:3932 https://access.redhat.com/errata/RHSA-2023:3932"
							},
							{
								"isprivate": "0",
								"commentid": "17422132",
								"comment_count": "33",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-29 12:28:55 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.4 Advanced Mission Critical Update Support\n  Red Hat Enterprise Linux 8.4 Update Services for SAP Solutions\n  Red Hat Enterprise Linux 8.4 Telecommunications Update Service\n\nVia RHSA-2023:3934 https://access.redhat.com/errata/RHSA-2023:3934"
							},
							{
								"isprivate": "0",
								"commentid": "17422172",
								"comment_count": "34",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-29 12:45:14 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.2 Advanced Update Support\n  Red Hat Enterprise Linux 8.2 Update Services for SAP Solutions\n  Red Hat Enterprise Linux 8.2 Telecommunications Update Service\n\nVia RHSA-2023:3935 https://access.redhat.com/errata/RHSA-2023:3935"
							},
							{
								"isprivate": "0",
								"commentid": "17422191",
								"comment_count": "35",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-06-29 13:01:54 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.1 Update Services for SAP Solutions\n\nVia RHSA-2023:3936 https://access.redhat.com/errata/RHSA-2023:3936"
							},
							{
								"isprivate": "0",
								"commentid": "17443840",
								"comment_count": "37",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-07-10 08:57:42 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.4 Advanced Mission Critical Update Support\n  Red Hat Enterprise Linux 8.4 Update Services for SAP Solutions\n  Red Hat Enterprise Linux 8.4 Telecommunications Update Service\n\nVia RHSA-2023:4004 https://access.redhat.com/errata/RHSA-2023:4004"
							},
							{
								"isprivate": "0",
								"commentid": "17444448",
								"comment_count": "38",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-07-10 12:22:08 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.4 Advanced Mission Critical Update Support\n  Red Hat Enterprise Linux 8.4 Update Services for SAP Solutions\n  Red Hat Enterprise Linux 8.4 Telecommunications Update Service\n\nVia RHSA-2023:4008 https://access.redhat.com/errata/RHSA-2023:4008"
							},
							{
								"isprivate": "0",
								"commentid": "17450311",
								"comment_count": "39",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-07-12 08:24:04 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.2 Advanced Update Support\n  Red Hat Enterprise Linux 8.2 Update Services for SAP Solutions\n  Red Hat Enterprise Linux 8.2 Telecommunications Update Service\n\nVia RHSA-2023:4038 https://access.redhat.com/errata/RHSA-2023:4038"
							},
							{
								"isprivate": "0",
								"commentid": "17450349",
								"comment_count": "40",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-07-12 08:26:11 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.6 Extended Update Support\n\nVia RHSA-2023:4032 https://access.redhat.com/errata/RHSA-2023:4032"
							},
							{
								"isprivate": "0",
								"commentid": "17465449",
								"comment_count": "41",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-07-18 14:52:50 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9.0 Extended Update Support\n\nVia RHSA-2023:4203 https://access.redhat.com/errata/RHSA-2023:4203"
							},
							{
								"isprivate": "0",
								"commentid": "17487163",
								"comment_count": "42",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-07-26 09:55:19 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Virtualization 4 for Red Hat Enterprise Linux 8\n\nVia RHSA-2023:4282 https://access.redhat.com/errata/RHSA-2023:4282"
							},
							{
								"isprivate": "0",
								"commentid": "17745653",
								"comment_count": "45",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-11-08 08:17:14 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n\nVia RHSA-2023:6793 https://access.redhat.com/errata/RHSA-2023:6793"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "17081580",
						"comment_count": "0",
						"who": {
							"text": "mrehak",
							"name": "Marian Rehak"
						},
						"bug_when": "2023-02-28 16:59:01 +0000",
						"thetext": "\nMore information about this security flaw is available in the following bug:\n\nhttp://bugzilla.redhat.com/show_bug.cgi?id=2173917\n\nDisclaimer: Community trackers are created by Red Hat Product Security team on a best effort basis. Package maintainers are required to ascertain if the flaw indeed affects their package, before starting the update process."
					},
					{
						"isprivate": "0",
						"commentid": "17081581",
						"comment_count": "1",
						"who": {
							"text": "mrehak",
							"name": "Marian Rehak"
						},
						"bug_when": "2023-02-28 16:59:03 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=high\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=2173917,2174018\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "17333090",
						"comment_count": "2",
						"who": {
							"text": "cstratak",
							"name": "Charalampos Stratakis"
						},
						"bug_when": "2023-05-29 16:58:40 +0000",
						"thetext": "PR's: https://src.fedoraproject.org/rpms/pypy/pull-requests"
					},
					{
						"isprivate": "0",
						"commentid": "17335495",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-05-30 15:00:17 +0000",
						"thetext": "FEDORA-2023-4f1864b5cb has been submitted as an update to Fedora 39. https://bodhi.fedoraproject.org/updates/FEDORA-2023-4f1864b5cb"
					},
					{
						"isprivate": "0",
						"commentid": "17335521",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-05-30 15:02:57 +0000",
						"thetext": "FEDORA-2023-acdfd145f2 has been submitted as an update to Fedora 37. https://bodhi.fedoraproject.org/updates/FEDORA-2023-acdfd145f2"
					},
					{
						"isprivate": "0",
						"commentid": "17335540",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-05-30 15:04:35 +0000",
						"thetext": "FEDORA-2023-4f1864b5cb has been pushed to the Fedora 39 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "17335836",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-05-30 16:19:58 +0000",
						"thetext": "FEDORA-2023-690e150a39 has been submitted as an update to Fedora 38. https://bodhi.fedoraproject.org/updates/FEDORA-2023-690e150a39"
					},
					{
						"isprivate": "0",
						"commentid": "17336736",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-05-31 01:28:38 +0000",
						"thetext": "FEDORA-2023-acdfd145f2 has been pushed to the Fedora 37 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2023-acdfd145f2`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2023-acdfd145f2\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "17336898",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-05-31 02:50:34 +0000",
						"thetext": "FEDORA-2023-690e150a39 has been pushed to the Fedora 38 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2023-690e150a39`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2023-690e150a39\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "17339447",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-05-31 17:32:04 +0000",
						"thetext": "FEDORA-2023-690e150a39 has been pushed to the Fedora 38 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "17373242",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-06-08 01:59:31 +0000",
						"thetext": "FEDORA-2023-acdfd145f2 has been pushed to the Fedora 37 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "pypy-7.3.11-3.fc38",
			"release_id": 66,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "pypy-debuginfo",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "aarch64"
					},
					{
						"name": "pypy-libs-debuginfo",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "aarch64"
					},
					{
						"name": "pypy",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "aarch64"
					},
					{
						"name": "pypy-devel",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "aarch64"
					},
					{
						"name": "pypy-debugsource-debuginfo",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "aarch64"
					},
					{
						"name": "pypy-libs",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "aarch64"
					},
					{
						"name": "pypy-debugsource",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "aarch64"
					}
				],
				"ppc64le": [
					{
						"name": "pypy-debuginfo",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "ppc64le"
					},
					{
						"name": "pypy",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "ppc64le"
					},
					{
						"name": "pypy-devel",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "ppc64le"
					},
					{
						"name": "pypy-libs-debuginfo",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "ppc64le"
					},
					{
						"name": "pypy-debugsource-debuginfo",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "ppc64le"
					},
					{
						"name": "pypy-libs",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "ppc64le"
					},
					{
						"name": "pypy-debugsource",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "pypy-libs",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "s390x"
					},
					{
						"name": "pypy-debugsource",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "s390x"
					},
					{
						"name": "pypy-debugsource-debuginfo",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "s390x"
					},
					{
						"name": "pypy-libs-debuginfo",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "s390x"
					},
					{
						"name": "pypy-devel",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "s390x"
					},
					{
						"name": "pypy",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "s390x"
					},
					{
						"name": "pypy-debuginfo",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "pypy",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "pypy-devel",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "x86_64"
					},
					{
						"name": "pypy-libs-debuginfo",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "x86_64"
					},
					{
						"name": "pypy-debugsource-debuginfo",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "x86_64"
					},
					{
						"name": "pypy-libs",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "x86_64"
					},
					{
						"name": "pypy",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "x86_64"
					},
					{
						"name": "pypy-debugsource",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "x86_64"
					},
					{
						"name": "pypy-debuginfo",
						"version": "7.3.11",
						"release": "3.fc38",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 3042633,
			"text": "This update has been submitted for testing by cstratak. ",
			"timestamp": "2023-05-30 16:19:56",
			"update_id": 514748,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3042634,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2023-05-30 16:19:56",
			"update_id": 514748,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3043283,
			"text": "This update has been pushed to testing.",
			"timestamp": "2023-05-31 02:51:06",
			"update_id": 514748,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3043438,
			"karma": 1,
			"timestamp": "2023-05-31 07:47:26",
			"update_id": 514748,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/665c5bc41bed444bc5fc8ea32da393449791968f9398dbe8ca045576e0ec52d3?s=24&d=retro",
				"email": "fzatlouk@redhat.com",
				"groups": [
					{
						"name": "qa-tools-sig"
					},
					{
						"name": "qa"
					},
					{
						"name": "packager"
					},
					{
						"name": "provenpackager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "sysadmin"
					},
					{
						"name": "ambassadors"
					},
					{
						"name": "sysadmin-qa"
					},
					{
						"name": "advocates"
					},
					{
						"name": "qa-admin"
					}
				],
				"id": 2240,
				"name": "frantisekz",
				"openid": "frantisekz.id.fedoraproject.org"
			},
			"user_id": 2240
		},
		{
			"id": 3043439,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2023-05-31 07:47:26",
			"update_id": 514748,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3044058,
			"text": "This update has been pushed to stable.",
			"timestamp": "2023-05-31 17:32:40",
			"update_id": 514748,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"critpath_groups": "",
	"date_approved": "2023-05-31 07:47:26",
	"date_pushed": "2023-05-31 17:29:34",
	"date_stable": "2023-05-31 17:29:34",
	"date_submitted": "2023-05-30 16:19:55",
	"date_testing": "2023-05-31 02:49:29",
	"karma": 1,
	"meets_testing_requirements": true,
	"notes": "Security fix for CVE-2023-24329",
	"pushed": true,
	"release": {
		"branch": "f38",
		"candidate_tag": "f38-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f38",
		"eol": "2024-05-21",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 38",
		"mail_template": "fedora_errata_template",
		"name": "F38",
		"override_tag": "f38-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f38-signing-pending",
		"pending_stable_tag": "f38-updates-pending",
		"pending_testing_tag": "f38-updates-testing-pending",
		"stable_tag": "f38-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f38-updates-testing",
		"version": "38"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "high",
	"stable_days": 7,
	"stable_karma": 1,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "pypy-7.3.11-3.fc38",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2023-690e150a39",
	"unstable_karma": -3,
	"updateid": "FEDORA-2023-690e150a39",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/af49eb5320c1c40d81a98d1fcdccc06c470c1458daab1a4f27be4cb170dbab3c?s=24&d=retro",
		"email": "cstratak@redhat.com",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "provenpackager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "modularity-wg"
			},
			{
				"name": "python-packagers-sig"
			}
		],
		"id": 2512,
		"name": "cstratak",
		"openid": "cstratak.id.fedoraproject.org"
	},
	"version_hash": "cba57fe02a552edbb4c68b4488ed3bfe3311e69d"
}
