{
	"alias": "FEDORA-2023-9078f609e6",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 2137775,
			"feedback": [
				{
					"bug_id": 2137775,
					"comment": {
						"id": 2850621,
						"karma": 1,
						"timestamp": "2023-01-19 18:22:47",
						"update_id": 474405,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/8364563f7a3e319a0f7ddf27dbe9945f8351d415cc7ae99cd3275291defec2b0?s=24&d=retro",
							"email": "eugenemah@gmail.com",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedora-hams"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 2935,
							"name": "imabug",
							"openid": "imabug.id.fedoraproject.org"
						},
						"user_id": 2935
					},
					"comment_id": 2850621,
					"karma": 1
				},
				{
					"bug_id": 2137775,
					"comment": {
						"id": 2851156,
						"karma": 1,
						"timestamp": "2023-01-20 05:31:16",
						"update_id": 474405,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/e0139d86a599e69cdbb69cb66873e910e1ced14de8faaa033811c4fc06067f93?s=24&d=retro",
							"email": "vascom2@gmail.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "provenpackager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 249,
							"name": "vascom",
							"openid": "vascom.id.fedoraproject.org"
						},
						"user_id": 249
					},
					"comment_id": 2851156,
					"karma": 1
				},
				{
					"bug_id": 2137775,
					"comment": {
						"id": 2852870,
						"karma": 1,
						"text": "Working fine here.",
						"timestamp": "2023-01-21 22:34:38",
						"update_id": 474409,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/83681a21ba31459f7d90616fc9043ed5465c66f4cf45969012311110125f969c?s=24&d=retro",
							"email": "nixuser@mail.com",
							"groups": [
								{
									"name": "qa"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 4756,
							"name": "nixuser",
							"openid": "nixuser.id.fedoraproject.org"
						},
						"user_id": 4756
					},
					"comment_id": 2852870,
					"karma": 1
				},
				{
					"bug_id": 2137775,
					"comment": {
						"id": 2852420,
						"karma": 1,
						"text": "Working OK so far.",
						"timestamp": "2023-01-21 04:06:19",
						"update_id": 474405,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/83681a21ba31459f7d90616fc9043ed5465c66f4cf45969012311110125f969c?s=24&d=retro",
							"email": "nixuser@mail.com",
							"groups": [
								{
									"name": "qa"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 4756,
							"name": "nixuser",
							"openid": "nixuser.id.fedoraproject.org"
						},
						"user_id": 4756
					},
					"comment_id": 2852420,
					"karma": 1
				},
				{
					"bug_id": 2137775,
					"comment": {
						"id": 2853990,
						"karma": 1,
						"timestamp": "2023-01-23 08:55:08",
						"update_id": 474409,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/e0db500976c6ad96a9b853578c37c53fc0ec241df3d8203ff7706191be3bf2b6?s=24&d=retro",
							"email": "nedal@posteo.de",
							"groups": [
								{
									"name": "ipausers"
								}
							],
							"id": 5498,
							"name": "nedal",
							"openid": "nedal.id.fedoraproject.org"
						},
						"user_id": 5498
					},
					"comment_id": 2853990,
					"karma": 1
				}
			],
			"title": "sudo-1.9.12p2 is available",
			"bugzilla": {
				"bug_id": "2137775",
				"creation_ts": "2022-10-26 07:30:09 +0000",
				"short_desc": "sudo-1.9.12p2 is available",
				"delta_ts": "2023-02-05 01:52:54 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "FutureFeature, Triaged",
				"priority": "unspecified",
				"bug_severity": "unspecified",
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "16733530",
						"comment_count": "0",
						"who": {
							"text": "upstream-release-monitoring",
							"name": "Upstream Release Monitoring"
						},
						"bug_when": "2022-10-26 07:30:09 +0000",
						"thetext": "Releases retrieved: 1.9.12\nUpstream release that is considered latest: 1.9.12\nCurrent version/release in rawhide: 1.9.11-4.p3.fc37\nURL: https://www.sudo.ws\n\nPlease consult the package updates policy before you issue an update to a stable branch: https://docs.fedoraproject.org/en-US/fesco/Updates_Policy/\n\n\nMore information about the service that created this bug can be found at: https://docs.fedoraproject.org/en-US/package-maintainers/Upstream_Release_Monitoring\n\n\nPlease keep in mind that with any upstream change, there may also be packaging changes that need to be made. Specifically, please remember that it is your responsibility to review the new version to ensure that the licensing is still correct and that no non-free or legally problematic items have been added upstream.\n\n\nBased on the information from Anitya: https://release-monitoring.org/project/4906/\n\n\nTo change the monitoring settings for the project, please visit:\nhttps://src.fedoraproject.org/rpms/sudo"
					},
					{
						"isprivate": "0",
						"commentid": "16733531",
						"comment_count": "1",
						"who": {
							"text": "upstream-release-monitoring",
							"name": "Upstream Release Monitoring"
						},
						"bug_when": "2022-10-26 07:30:14 +0000",
						"thetext": "Scratch build failed. Details below:\n\nBuilderException: Build failed:\nCommand '['rpmbuild', '-D', '_sourcedir .', '-D', '_topdir .', '-bs', '/var/tmp/thn-z35fddm3/sudo.spec']' returned non-zero exit status 1.\n\nStdOut:\nerror: Bad source: ./sudo-1.9.12p3.tar.gz: No such file or directory\n\n\nTraceback:\n  File \"/usr/local/lib/python3.10/site-packages/hotness/use_cases/package_scratch_build_use_case.py\", line 56, in build\n    result = self.builder.build(request.package, request.opts)\n  File \"/usr/local/lib/python3.10/site-packages/hotness/builders/koji.py\", line 188, in build\n    raise BuilderException(\n\nIf you think this issue is caused by some bug in the-new-hotness, please report it on the-new-hotness issue tracker: https://github.com/fedora-infra/the-new-hotness/issues"
					},
					{
						"isprivate": "0",
						"commentid": "16756993",
						"comment_count": "2",
						"who": {
							"text": "upstream-release-monitoring",
							"name": "Upstream Release Monitoring"
						},
						"bug_when": "2022-11-05 02:42:17 +0000",
						"thetext": "Releases retrieved: 1.9.12p1\nUpstream release that is considered latest: 1.9.12p1\nCurrent version/release in rawhide: 1.9.11-4.p3.fc37\nURL: https://www.sudo.ws\n\nPlease consult the package updates policy before you issue an update to a stable branch: https://docs.fedoraproject.org/en-US/fesco/Updates_Policy/\n\n\nMore information about the service that created this bug can be found at: https://docs.fedoraproject.org/en-US/package-maintainers/Upstream_Release_Monitoring\n\n\nPlease keep in mind that with any upstream change, there may also be packaging changes that need to be made. Specifically, please remember that it is your responsibility to review the new version to ensure that the licensing is still correct and that no non-free or legally problematic items have been added upstream.\n\n\nBased on the information from Anitya: https://release-monitoring.org/project/4906/\n\n\nTo change the monitoring settings for the project, please visit:\nhttps://src.fedoraproject.org/rpms/sudo"
					},
					{
						"isprivate": "0",
						"commentid": "16756994",
						"comment_count": "3",
						"who": {
							"text": "upstream-release-monitoring",
							"name": "Upstream Release Monitoring"
						},
						"bug_when": "2022-11-05 02:42:21 +0000",
						"thetext": "Scratch build failed. Details below:\n\nBuilderException: Build failed:\nCommand '['rpmbuild', '-D', '_sourcedir .', '-D', '_topdir .', '-bs', '/var/tmp/thn-g2f6pdey/sudo.spec']' returned non-zero exit status 1.\n\nStdOut:\nerror: Bad source: ./sudo-1.9.12p1p3.tar.gz: No such file or directory\n\n\nTraceback:\n  File \"/usr/local/lib/python3.10/site-packages/hotness/use_cases/package_scratch_build_use_case.py\", line 56, in build\n    result = self.builder.build(request.package, request.opts)\n  File \"/usr/local/lib/python3.10/site-packages/hotness/builders/koji.py\", line 188, in build\n    raise BuilderException(\n\nIf you think this issue is caused by some bug in the-new-hotness, please report it on the-new-hotness issue tracker: https://github.com/fedora-infra/the-new-hotness/issues"
					},
					{
						"isprivate": "0",
						"commentid": "16979004",
						"comment_count": "4",
						"who": {
							"text": "upstream-release-monitoring",
							"name": "Upstream Release Monitoring"
						},
						"bug_when": "2023-01-18 17:19:32 +0000",
						"thetext": "Releases retrieved: 1.9.12p2\nUpstream release that is considered latest: 1.9.12p2\nCurrent version/release in rawhide: 1.9.11-4.p3.fc37\nURL: https://www.sudo.ws\n\nPlease consult the package updates policy before you issue an update to a stable branch: https://docs.fedoraproject.org/en-US/fesco/Updates_Policy/\n\n\nMore information about the service that created this bug can be found at: https://docs.fedoraproject.org/en-US/package-maintainers/Upstream_Release_Monitoring\n\n\nPlease keep in mind that with any upstream change, there may also be packaging changes that need to be made. Specifically, please remember that it is your responsibility to review the new version to ensure that the licensing is still correct and that no non-free or legally problematic items have been added upstream.\n\n\nBased on the information from Anitya: https://release-monitoring.org/project/4906/\n\n\nTo change the monitoring settings for the project, please visit:\nhttps://src.fedoraproject.org/rpms/sudo"
					},
					{
						"isprivate": "0",
						"commentid": "16979005",
						"comment_count": "5",
						"who": {
							"text": "upstream-release-monitoring",
							"name": "Upstream Release Monitoring"
						},
						"bug_when": "2023-01-18 17:19:36 +0000",
						"thetext": "Scratch build failed. Details below:\n\nBuilderException: Build failed:\nCommand '['rpmbuild', '-D', '_sourcedir .', '-D', '_topdir .', '-bs', '/var/tmp/thn-i1cr8s0d/sudo.spec']' returned non-zero exit status 1.\n\nStdOut:\nerror: Bad source: ./sudo-1.9.12p2p3.tar.gz: No such file or directory\n\n\nTraceback:\n  File \"/usr/local/lib/python3.10/site-packages/hotness/use_cases/package_scratch_build_use_case.py\", line 56, in build\n    result = self.builder.build(request.package, request.opts)\n  File \"/usr/local/lib/python3.10/site-packages/hotness/builders/koji.py\", line 188, in build\n    raise BuilderException(\n\nIf you think this issue is caused by some bug in the-new-hotness, please report it on the-new-hotness issue tracker: https://github.com/fedora-infra/the-new-hotness/issues"
					},
					{
						"isprivate": "0",
						"commentid": "16981118",
						"comment_count": "6",
						"who": {
							"text": "rsroka",
							"name": "Radovan Sroka"
						},
						"bug_when": "2023-01-19 12:47:09 +0000",
						"thetext": "*** Bug 2047541 has been marked as a duplicate of this bug. ***"
					},
					{
						"isprivate": "0",
						"commentid": "16981389",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-01-19 13:49:00 +0000",
						"thetext": "FEDORA-2023-ccd023b9ee has been submitted as an update to Fedora 38. https://bodhi.fedoraproject.org/updates/FEDORA-2023-ccd023b9ee"
					},
					{
						"isprivate": "0",
						"commentid": "16981618",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-01-19 14:32:17 +0000",
						"thetext": "FEDORA-2023-9078f609e6 has been submitted as an update to Fedora 37. https://bodhi.fedoraproject.org/updates/FEDORA-2023-9078f609e6"
					},
					{
						"isprivate": "0",
						"commentid": "16981720",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-01-19 15:01:54 +0000",
						"thetext": "FEDORA-2023-298c136eee has been submitted as an update to Fedora 36. https://bodhi.fedoraproject.org/updates/FEDORA-2023-298c136eee"
					},
					{
						"isprivate": "0",
						"commentid": "16982177",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-01-19 17:54:57 +0000",
						"thetext": "FEDORA-2023-ccd023b9ee has been pushed to the Fedora 38 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "16985810",
						"comment_count": "11",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-01-21 03:31:33 +0000",
						"thetext": "FEDORA-2023-9078f609e6 has been pushed to the Fedora 37 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2023-9078f609e6`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2023-9078f609e6\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "16986338",
						"comment_count": "12",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-01-21 16:28:53 +0000",
						"thetext": "FEDORA-2023-298c136eee has been pushed to the Fedora 36 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2023-298c136eee`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2023-298c136eee\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "16986731",
						"comment_count": "13",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-01-22 01:42:28 +0000",
						"thetext": "FEDORA-2023-9078f609e6 has been pushed to the Fedora 37 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "17022831",
						"comment_count": "14",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-02-05 01:52:54 +0000",
						"thetext": "FEDORA-2023-298c136eee has been pushed to the Fedora 36 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 2162042,
			"feedback": [
				{
					"bug_id": 2162042,
					"comment": {
						"id": 2850621,
						"karma": 1,
						"timestamp": "2023-01-19 18:22:47",
						"update_id": 474405,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/8364563f7a3e319a0f7ddf27dbe9945f8351d415cc7ae99cd3275291defec2b0?s=24&d=retro",
							"email": "eugenemah@gmail.com",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedora-hams"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 2935,
							"name": "imabug",
							"openid": "imabug.id.fedoraproject.org"
						},
						"user_id": 2935
					},
					"comment_id": 2850621
				},
				{
					"bug_id": 2162042,
					"comment": {
						"id": 2851156,
						"karma": 1,
						"timestamp": "2023-01-20 05:31:16",
						"update_id": 474405,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/e0139d86a599e69cdbb69cb66873e910e1ced14de8faaa033811c4fc06067f93?s=24&d=retro",
							"email": "vascom2@gmail.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "provenpackager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 249,
							"name": "vascom",
							"openid": "vascom.id.fedoraproject.org"
						},
						"user_id": 249
					},
					"comment_id": 2851156,
					"karma": 1
				},
				{
					"bug_id": 2162042,
					"comment": {
						"id": 2852420,
						"karma": 1,
						"text": "Working OK so far.",
						"timestamp": "2023-01-21 04:06:19",
						"update_id": 474405,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/83681a21ba31459f7d90616fc9043ed5465c66f4cf45969012311110125f969c?s=24&d=retro",
							"email": "nixuser@mail.com",
							"groups": [
								{
									"name": "qa"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 4756,
							"name": "nixuser",
							"openid": "nixuser.id.fedoraproject.org"
						},
						"user_id": 4756
					},
					"comment_id": 2852420
				}
			],
			"security": true,
			"title": "CVE-2023-22809 sudo: arbitrary file write with privileges of the RunAs user [fedora-37]",
			"bugzilla": {
				"bug_id": "2162042",
				"creation_ts": "2023-01-18 16:34:22 +0000",
				"short_desc": "CVE-2023-22809 sudo: arbitrary file write with privileges of the RunAs user [fedora-37]",
				"delta_ts": "2023-01-22 01:42:30 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "high",
				"bug_severity": "high",
				"blocked": [
					{
						"bug_id": "2161142",
						"alias": "CVE-2023-22809",
						"creation_ts": "2023-01-16 05:26:29 +0000",
						"short_desc": "CVE-2023-22809 sudo: arbitrary file write with privileges of the RunAs user",
						"delta_ts": "2023-05-23 14:00:34 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Reopened, Security",
						"priority": "high",
						"bug_severity": "high",
						"depends_on": [
							"2161216",
							"2161217",
							"2161218",
							"2161219",
							"2161220",
							"2161221",
							"2161222",
							"2161223",
							"2161224",
							"2161225",
							"2161268",
							"2162041",
							"2162042",
							"2164759",
							"2186685",
							"2186686",
							"2186687"
						],
						"blocked": [
							{
								"bug_id": "2160742",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2023:3276",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "16968946",
								"comment_count": "0",
								"who": {
									"text": "saroy",
									"name": "Sandipan Roy"
								},
								"bug_when": "2023-01-16 05:26:29 +0000",
								"thetext": "Vulnerability in the way sudoedit handles user-provided environment variables. This leads to arbitrary file write with privileges of the RunAs user (usually root). The prerequisite for exploitation is that the current user must be authorized by the sudoers policy to edit a file using sudoedit. This issue affects all Sudo versions <= 1.9.12p1 and was assigned CVE-2023-22809."
							},
							{
								"isprivate": "0",
								"commentid": "16969508",
								"comment_count": "1",
								"who": {
									"text": "rsroka",
									"name": "Radovan Sroka"
								},
								"bug_when": "2023-01-16 09:25:59 +0000",
								"thetext": "Do we have a reproducer?"
							},
							{
								"isprivate": "0",
								"commentid": "16978868",
								"comment_count": "6",
								"who": {
									"text": "zmiele",
									"name": "Zack Miele"
								},
								"bug_when": "2023-01-18 16:34:30 +0000",
								"thetext": "Created sudo tracking bugs for this issue:\n\nAffects: fedora-36 [bug 2162041]\nAffects: fedora-37 [bug 2162042]"
							},
							{
								"isprivate": "0",
								"commentid": "16988604",
								"comment_count": "7",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-01-23 08:56:45 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.1 Update Services for SAP Solutions\n\nVia RHSA-2023:0280 https://access.redhat.com/errata/RHSA-2023:0280"
							},
							{
								"isprivate": "0",
								"commentid": "16988606",
								"comment_count": "8",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-01-23 08:57:49 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2023:0282 https://access.redhat.com/errata/RHSA-2023:0282"
							},
							{
								"isprivate": "0",
								"commentid": "16988649",
								"comment_count": "9",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-01-23 09:16:34 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.6 Extended Update Support\n\nVia RHSA-2023:0283 https://access.redhat.com/errata/RHSA-2023:0283"
							},
							{
								"isprivate": "0",
								"commentid": "16988654",
								"comment_count": "10",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-01-23 09:17:40 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9.0 Extended Update Support\n\nVia RHSA-2023:0281 https://access.redhat.com/errata/RHSA-2023:0281"
							},
							{
								"isprivate": "0",
								"commentid": "16988658",
								"comment_count": "11",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-01-23 09:18:11 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2023:0284 https://access.redhat.com/errata/RHSA-2023:0284"
							},
							{
								"isprivate": "0",
								"commentid": "16988682",
								"comment_count": "12",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-01-23 09:19:15 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.2 Advanced Update Support\n  Red Hat Enterprise Linux 8.2 Update Services for SAP Solutions\n  Red Hat Enterprise Linux 8.2 Telecommunications Update Service\n\nVia RHSA-2023:0292 https://access.redhat.com/errata/RHSA-2023:0292"
							},
							{
								"isprivate": "0",
								"commentid": "16988694",
								"comment_count": "13",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-01-23 09:19:56 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 6 Extended Lifecycle Support\n\nVia RHSA-2023:0287 https://access.redhat.com/errata/RHSA-2023:0287"
							},
							{
								"isprivate": "0",
								"commentid": "16988706",
								"comment_count": "14",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-01-23 09:20:13 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.4 Extended Update Support\n\nVia RHSA-2023:0293 https://access.redhat.com/errata/RHSA-2023:0293"
							},
							{
								"isprivate": "0",
								"commentid": "16988755",
								"comment_count": "15",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-01-23 09:22:31 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2023:0291 https://access.redhat.com/errata/RHSA-2023:0291"
							},
							{
								"isprivate": "0",
								"commentid": "17004123",
								"comment_count": "18",
								"who": {
									"text": "prodsec-dev",
									"name": "Product Security DevOps Team"
								},
								"bug_when": "2023-01-28 17:22:09 +0000",
								"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2023-22809"
							},
							{
								"isprivate": "0",
								"commentid": "17040740",
								"comment_count": "30",
								"who": {
									"text": "prodsec-dev",
									"name": "Product Security DevOps Team"
								},
								"bug_when": "2023-02-12 09:39:27 +0000",
								"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2023-22809"
							},
							{
								"isprivate": "0",
								"commentid": "17063333",
								"comment_count": "31",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-02-21 10:40:32 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Virtualization 4 for Red Hat Enterprise Linux 8\n\nVia RHSA-2023:0859 https://access.redhat.com/errata/RHSA-2023:0859"
							},
							{
								"isprivate": "0",
								"commentid": "17310111",
								"comment_count": "33",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-05-23 09:15:23 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7.4 Advanced Update Support\n\nVia RHSA-2023:3264 https://access.redhat.com/errata/RHSA-2023:3264"
							},
							{
								"isprivate": "0",
								"commentid": "17310116",
								"comment_count": "34",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-05-23 09:15:48 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7.6 Advanced Update Support\n\nVia RHSA-2023:3262 https://access.redhat.com/errata/RHSA-2023:3262"
							},
							{
								"isprivate": "0",
								"commentid": "17311041",
								"comment_count": "35",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-05-23 14:00:31 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7.7 Advanced Update Support\n  Red Hat Enterprise Linux 7.7 Update Services for SAP Solutions\n  Red Hat Enterprise Linux 7.7 Telco Extended Update Support\n\nVia RHSA-2023:3276 https://access.redhat.com/errata/RHSA-2023:3276"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "16978866",
						"comment_count": "0",
						"who": {
							"text": "zmiele",
							"name": "Zack Miele"
						},
						"bug_when": "2023-01-18 16:34:22 +0000",
						"thetext": "\nMore information about this security flaw is available in the following bug:\n\nhttp://bugzilla.redhat.com/show_bug.cgi?id=2161142\n\nDisclaimer: Community trackers are created by Red Hat Product Security team on a best effort basis. Package maintainers are required to ascertain if the flaw indeed affects their package, before starting the update process."
					},
					{
						"isprivate": "0",
						"commentid": "16978867",
						"comment_count": "1",
						"who": {
							"text": "zmiele",
							"name": "Zack Miele"
						},
						"bug_when": "2023-01-18 16:34:24 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=high\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=2161142,2162042\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "16981619",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-01-19 14:32:20 +0000",
						"thetext": "FEDORA-2023-9078f609e6 has been submitted as an update to Fedora 37. https://bodhi.fedoraproject.org/updates/FEDORA-2023-9078f609e6"
					},
					{
						"isprivate": "0",
						"commentid": "16985812",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-01-21 03:31:36 +0000",
						"thetext": "FEDORA-2023-9078f609e6 has been pushed to the Fedora 37 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2023-9078f609e6`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2023-9078f609e6\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "16986732",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2023-01-22 01:42:30 +0000",
						"thetext": "FEDORA-2023-9078f609e6 has been pushed to the Fedora 37 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "sudo-1.9.12-1.p2.fc37",
			"release_id": 62,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "sudo-logsrvd-debuginfo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "aarch64"
					},
					{
						"name": "sudo-python-plugin-debuginfo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "aarch64"
					},
					{
						"name": "sudo-devel",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "aarch64"
					},
					{
						"name": "sudo-logsrvd",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "aarch64"
					},
					{
						"name": "sudo-python-plugin",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "aarch64"
					},
					{
						"name": "sudo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "aarch64"
					},
					{
						"name": "sudo-debuginfo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "aarch64"
					},
					{
						"name": "sudo-debugsource",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "aarch64"
					}
				],
				"i686": [
					{
						"name": "sudo-logsrvd-debuginfo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "i686"
					},
					{
						"name": "sudo-debuginfo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "i686"
					},
					{
						"name": "sudo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "i686"
					},
					{
						"name": "sudo-debugsource",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "i686"
					},
					{
						"name": "sudo-logsrvd",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "i686"
					},
					{
						"name": "sudo-python-plugin-debuginfo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "i686"
					},
					{
						"name": "sudo-python-plugin",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "i686"
					},
					{
						"name": "sudo-devel",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "i686"
					}
				],
				"ppc64le": [
					{
						"name": "sudo-devel",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "ppc64le"
					},
					{
						"name": "sudo-logsrvd-debuginfo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "ppc64le"
					},
					{
						"name": "sudo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "ppc64le"
					},
					{
						"name": "sudo-python-plugin",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "ppc64le"
					},
					{
						"name": "sudo-python-plugin-debuginfo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "ppc64le"
					},
					{
						"name": "sudo-logsrvd",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "ppc64le"
					},
					{
						"name": "sudo-debuginfo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "ppc64le"
					},
					{
						"name": "sudo-debugsource",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "sudo-debuginfo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "s390x"
					},
					{
						"name": "sudo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "s390x"
					},
					{
						"name": "sudo-logsrvd-debuginfo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "s390x"
					},
					{
						"name": "sudo-debugsource",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "s390x"
					},
					{
						"name": "sudo-logsrvd",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "s390x"
					},
					{
						"name": "sudo-python-plugin-debuginfo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "s390x"
					},
					{
						"name": "sudo-python-plugin",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "s390x"
					},
					{
						"name": "sudo-devel",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "sudo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "sudo-python-plugin-debuginfo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "x86_64"
					},
					{
						"name": "sudo-debuginfo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "x86_64"
					},
					{
						"name": "sudo-logsrvd-debuginfo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "x86_64"
					},
					{
						"name": "sudo",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "x86_64"
					},
					{
						"name": "sudo-logsrvd",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "x86_64"
					},
					{
						"name": "sudo-debugsource",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "x86_64"
					},
					{
						"name": "sudo-python-plugin",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "x86_64"
					},
					{
						"name": "sudo-devel",
						"version": "1.9.12",
						"release": "1.p2.fc37",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 2850454,
			"text": "This update has been submitted for testing by rsroka. ",
			"timestamp": "2023-01-19 14:32:14",
			"update_id": 474405,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2850455,
			"text": "This update's test gating status has been changed to 'waiting'.",
			"timestamp": "2023-01-19 14:32:15",
			"update_id": 474405,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2850458,
			"text": "rsroka edited this update.",
			"timestamp": "2023-01-19 14:33:51",
			"update_id": 474405,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2850459,
			"text": "rsroka edited this update.",
			"timestamp": "2023-01-19 14:34:07",
			"update_id": 474405,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2850542,
			"text": "This update's test gating status has been changed to 'failed'.",
			"timestamp": "2023-01-19 16:45:59",
			"update_id": 474405,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2850548,
			"text": "This update's test gating status has been changed to 'passed'.",
			"timestamp": "2023-01-19 16:53:01",
			"update_id": 474405,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"bug_feedback": [
				{
					"bug": {
						"bug_id": 2137775,
						"title": "sudo-1.9.12p2 is available"
					},
					"bug_id": 2137775,
					"comment_id": 2850621,
					"karma": 1
				},
				{
					"bug": {
						"bug_id": 2162042,
						"security": true,
						"title": "CVE-2023-22809 sudo: arbitrary file write with privileges of the RunAs user [fedora-37]"
					},
					"bug_id": 2162042,
					"comment_id": 2850621
				}
			],
			"id": 2850621,
			"karma": 1,
			"timestamp": "2023-01-19 18:22:47",
			"update_id": 474405,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/8364563f7a3e319a0f7ddf27dbe9945f8351d415cc7ae99cd3275291defec2b0?s=24&d=retro",
				"email": "eugenemah@gmail.com",
				"groups": [
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedora-hams"
					},
					{
						"name": "trust admins"
					}
				],
				"id": 2935,
				"name": "imabug",
				"openid": "imabug.id.fedoraproject.org"
			},
			"user_id": 2935
		},
		{
			"bug_feedback": [
				{
					"bug": {
						"bug_id": 2137775,
						"title": "sudo-1.9.12p2 is available"
					},
					"bug_id": 2137775,
					"comment_id": 2851156,
					"karma": 1
				},
				{
					"bug": {
						"bug_id": 2162042,
						"security": true,
						"title": "CVE-2023-22809 sudo: arbitrary file write with privileges of the RunAs user [fedora-37]"
					},
					"bug_id": 2162042,
					"comment_id": 2851156,
					"karma": 1
				}
			],
			"id": 2851156,
			"karma": 1,
			"timestamp": "2023-01-20 05:31:16",
			"update_id": 474405,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/e0139d86a599e69cdbb69cb66873e910e1ced14de8faaa033811c4fc06067f93?s=24&d=retro",
				"email": "vascom2@gmail.com",
				"groups": [
					{
						"name": "packager"
					},
					{
						"name": "provenpackager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "trust admins"
					}
				],
				"id": 249,
				"name": "vascom",
				"openid": "vascom.id.fedoraproject.org"
			},
			"user_id": 249
		},
		{
			"id": 2852364,
			"text": "This update has been pushed to testing.",
			"timestamp": "2023-01-21 03:32:41",
			"update_id": 474405,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2852376,
			"text": "This update can be pushed to stable now if the maintainer wishes",
			"timestamp": "2023-01-21 03:33:51",
			"update_id": 474405,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"bug_feedback": [
				{
					"bug": {
						"bug_id": 2137775,
						"title": "sudo-1.9.12p2 is available"
					},
					"bug_id": 2137775,
					"comment_id": 2852420,
					"karma": 1
				},
				{
					"bug": {
						"bug_id": 2162042,
						"security": true,
						"title": "CVE-2023-22809 sudo: arbitrary file write with privileges of the RunAs user [fedora-37]"
					},
					"bug_id": 2162042,
					"comment_id": 2852420
				}
			],
			"id": 2852420,
			"karma": 1,
			"text": "Working OK so far.",
			"timestamp": "2023-01-21 04:06:19",
			"update_id": 474405,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/83681a21ba31459f7d90616fc9043ed5465c66f4cf45969012311110125f969c?s=24&d=retro",
				"email": "nixuser@mail.com",
				"groups": [
					{
						"name": "qa"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "trust admins"
					}
				],
				"id": 4756,
				"name": "nixuser",
				"openid": "nixuser.id.fedoraproject.org"
			},
			"user_id": 4756
		},
		{
			"id": 2852421,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2023-01-21 04:06:19",
			"update_id": 474405,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2852464,
			"karma": 1,
			"text": "Works.",
			"timestamp": "2023-01-21 05:22:03",
			"update_id": 474405,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/1a8afd83231ef5ba905344806ba95b39f2abd77b399b0ee217ec3e6fa30a4825?s=24&d=retro",
				"email": "bojan@rexursive.com",
				"groups": [
					{
						"name": "packager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					}
				],
				"id": 198,
				"name": "bojan",
				"openid": "bojan.id.fedoraproject.org"
			},
			"user_id": 198
		},
		{
			"id": 2853073,
			"text": "This update has been pushed to stable.",
			"timestamp": "2023-01-22 01:44:48",
			"update_id": 474405,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"critpath": true,
	"date_approved": "2023-01-21 05:22:03",
	"date_modified": "2023-01-19 14:34:07",
	"date_pushed": "2023-01-22 01:40:20",
	"date_stable": "2023-01-22 01:40:20",
	"date_submitted": "2023-01-19 14:32:13",
	"date_testing": "2023-01-21 03:30:43",
	"karma": 4,
	"meets_testing_requirements": true,
	"notes": "Rebase to sudo-1.9.12p2\n\n- security fix for CVE-2023-22809\n\n",
	"pushed": true,
	"release": {
		"branch": "f37",
		"candidate_tag": "f37-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f37",
		"eol": "2023-12-05",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 37",
		"mail_template": "fedora_errata_template",
		"name": "F37",
		"override_tag": "f37-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f37-signing-pending",
		"pending_stable_tag": "f37-updates-pending",
		"pending_testing_tag": "f37-updates-testing-pending",
		"stable_tag": "f37-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f37-updates-testing",
		"version": "37"
	},
	"require_bugs": true,
	"severity": "high",
	"stable_days": 14,
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "passed",
	"title": "sudo-1.9.12-1.p2.fc37",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2023-9078f609e6",
	"unstable_karma": -3,
	"updateid": "FEDORA-2023-9078f609e6",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/39df0f0f67488aa1503694ae2be6d7dad131b28a334a62c33418cb2cb213a81f?s=24&d=retro",
		"email": "rsroka@redhat.com",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			}
		],
		"id": 3185,
		"name": "rsroka",
		"openid": "rsroka.id.fedoraproject.org"
	},
	"version_hash": "03948777b02bb6814af752bc25b2ceeacfa4919c"
}
