{
	"alias": "FEDORA-2022-b499f2a9c6",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 2076531,
			"security": true,
			"title": "CVE-2015-20107 pypy3.8: python(mailcap): findmatch() function does not sanitise the second argument [fedora-all]",
			"bugzilla": {
				"bug_id": "2076531",
				"creation_ts": "2022-04-19 09:45:48 +0000",
				"short_desc": "CVE-2015-20107 pypy3.8: python(mailcap): findmatch() function does not sanitise the second argument [fedora-all]",
				"delta_ts": "2022-07-08 01:36:56 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "2075390",
						"alias": "CVE-2015-20107",
						"creation_ts": "2022-04-14 05:03:43 +0000",
						"short_desc": "CVE-2015-20107 python: mailcap: findmatch() function does not sanitize the second argument",
						"delta_ts": "2022-12-05 01:32:53 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"2076507",
							"2076508",
							"2076509",
							"2076510",
							"2076511",
							"2076512",
							"2076513",
							"2076514",
							"2076515",
							"2076516",
							"2076526",
							"2076530",
							"2076531",
							"2076532",
							"2076533",
							"2077865",
							"2077866",
							"2077867",
							"2077868",
							"2077869",
							"2077871",
							"2077872",
							"2077873",
							"2077874",
							"2077875",
							"2077876",
							"2077877",
							"2084457",
							"2125237"
						],
						"blocked": [
							{
								"bug_id": "2075391",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2022:8353",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "16145012",
								"comment_count": "0",
								"who": {
									"text": "saroy",
									"name": "Sandipan Roy"
								},
								"bug_when": "2022-04-14 05:03:43 +0000",
								"thetext": "A command injection vulnerability was found in Python 2.x and 3.x, specifically within the mailcap module. Mailcap core-module is based on the format documented in RFC 1524. The “findmatch()” function does not sanitise the second argument (filename). As a result, the legitimate command (that is used for opening the specified mime type) is concatenated with an arbitrary command, injected by an attacker."
							},
							{
								"isprivate": "0",
								"commentid": "16150703",
								"comment_count": "1",
								"who": {
									"text": "saroy",
									"name": "Sandipan Roy"
								},
								"bug_when": "2022-04-18 04:58:25 +0000",
								"thetext": "Ref:\nhttps://github.com/python/cpython/issues/68966\nhttps://bugs.python.org/issue24778"
							},
							{
								"isprivate": "0",
								"commentid": "16153625",
								"comment_count": "2",
								"who": {
									"text": "vstinner",
									"name": "Victor Stinner"
								},
								"bug_when": "2022-04-19 08:34:56 +0000",
								"thetext": "Public announcement: https://mail.python.org/archives/list/security-announce@python.org/thread/QDSXNCW77UGULFG2JMDFZQ7H4DIR32LA/"
							},
							{
								"isprivate": "0",
								"commentid": "16153707",
								"comment_count": "3",
								"who": {
									"text": "saroy",
									"name": "Sandipan Roy"
								},
								"bug_when": "2022-04-19 09:01:05 +0000",
								"thetext": "Created mingw-python3 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2076508]\n\n\nCreated python2.7 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2076509]\n\n\nCreated python3.10 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2076510]\n\n\nCreated python3.11 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2076511]\n\n\nCreated python3.5 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2076512]\n\n\nCreated python3.6 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2076513]\n\n\nCreated python3.7 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2076514]\n\n\nCreated python3.8 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2076515]\n\n\nCreated python3.9 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2076516]\n\n\nCreated python34 tracking bugs for this issue:\n\nAffects: epel-all [bug 2076507]"
							},
							{
								"isprivate": "0",
								"commentid": "16153799",
								"comment_count": "4",
								"who": {
									"text": "saroy",
									"name": "Sandipan Roy"
								},
								"bug_when": "2022-04-19 09:40:09 +0000",
								"thetext": "Created pypy3 tracking bugs for this issue:\n\nAffects: fedora-34 [bug 2076526]"
							},
							{
								"isprivate": "0",
								"commentid": "16153826",
								"comment_count": "5",
								"who": {
									"text": "saroy",
									"name": "Sandipan Roy"
								},
								"bug_when": "2022-04-19 09:46:17 +0000",
								"thetext": "Created pypy tracking bugs for this issue:\n\nAffects: fedora-all [bug 2076533]\n\n\nCreated pypy3.7 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2076530]\n\n\nCreated pypy3.8 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2076531]\n\n\nCreated pypy3.9 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2076532]"
							},
							{
								"isprivate": "0",
								"commentid": "16180510",
								"comment_count": "12",
								"who": {
									"text": "pviktori",
									"name": "Petr Viktorin (pviktori)"
								},
								"bug_when": "2022-04-27 16:33:23 +0000",
								"thetext": "Here's a possible solution -- make mailcap fail to match with unsafe filenames: https://github.com/python/cpython/pull/91993\nWDYT?"
							},
							{
								"isprivate": "0",
								"commentid": "16632543",
								"comment_count": "15",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2022-09-13 09:45:18 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2022:6457 https://access.redhat.com/errata/RHSA-2022:6457"
							},
							{
								"isprivate": "0",
								"commentid": "16682598",
								"comment_count": "16",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2022-10-03 15:19:58 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n\nVia RHSA-2022:6766 https://access.redhat.com/errata/RHSA-2022:6766"
							},
							{
								"isprivate": "0",
								"commentid": "16765704",
								"comment_count": "17",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2022-11-08 09:44:06 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2022:7581 https://access.redhat.com/errata/RHSA-2022:7581"
							},
							{
								"isprivate": "0",
								"commentid": "16765786",
								"comment_count": "18",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2022-11-08 09:46:34 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2022:7592 https://access.redhat.com/errata/RHSA-2022:7592"
							},
							{
								"isprivate": "0",
								"commentid": "16765787",
								"comment_count": "19",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2022-11-08 09:46:36 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2022:7593 https://access.redhat.com/errata/RHSA-2022:7593"
							},
							{
								"isprivate": "0",
								"commentid": "16789701",
								"comment_count": "20",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2022-11-15 11:01:35 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2022:8353 https://access.redhat.com/errata/RHSA-2022:8353"
							},
							{
								"isprivate": "0",
								"commentid": "16848619",
								"comment_count": "21",
								"who": {
									"text": "prodsec-dev",
									"name": "Product Security DevOps Team"
								},
								"bug_when": "2022-12-05 01:32:50 +0000",
								"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2015-20107"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "16153818",
						"comment_count": "0",
						"who": {
							"text": "saroy",
							"name": "Sandipan Roy"
						},
						"bug_when": "2022-04-19 09:45:48 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "16153819",
						"comment_count": "1",
						"who": {
							"text": "saroy",
							"name": "Sandipan Roy"
						},
						"bug_when": "2022-04-19 09:45:52 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=2075390,2076531\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "16396544",
						"comment_count": "2",
						"who": {
							"text": "cstratak",
							"name": "Charalampos Stratakis"
						},
						"bug_when": "2022-06-28 23:30:43 +0000",
						"thetext": "PR's:\n\nRawhide: https://src.fedoraproject.org/rpms/pypy3.8/pull-request/15\nF36: https://src.fedoraproject.org/rpms/pypy3.8/pull-request/16\nF35: https://src.fedoraproject.org/rpms/pypy3.8/pull-request/17"
					},
					{
						"isprivate": "0",
						"commentid": "16399794",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-06-29 18:34:19 +0000",
						"thetext": "FEDORA-2022-9cd41b6709 has been submitted as an update to Fedora 35. https://bodhi.fedoraproject.org/updates/FEDORA-2022-9cd41b6709"
					},
					{
						"isprivate": "0",
						"commentid": "16399796",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-06-29 18:34:55 +0000",
						"thetext": "FEDORA-2022-b499f2a9c6 has been submitted as an update to Fedora 36. https://bodhi.fedoraproject.org/updates/FEDORA-2022-b499f2a9c6"
					},
					{
						"isprivate": "0",
						"commentid": "16400530",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-06-30 01:25:18 +0000",
						"thetext": "FEDORA-2022-9cd41b6709 has been pushed to the Fedora 35 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2022-9cd41b6709`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2022-9cd41b6709\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "16400560",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-06-30 01:33:43 +0000",
						"thetext": "FEDORA-2022-b499f2a9c6 has been pushed to the Fedora 36 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2022-b499f2a9c6`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2022-b499f2a9c6\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "16423781",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-07-08 01:16:23 +0000",
						"thetext": "FEDORA-2022-b499f2a9c6 has been pushed to the Fedora 36 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "16423816",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-07-08 01:36:56 +0000",
						"thetext": "FEDORA-2022-9cd41b6709 has been pushed to the Fedora 35 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "pypy3.8-7.3.9-2.3.8.fc36",
			"release_id": 56,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "pypy3.8-devel",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "aarch64"
					},
					{
						"name": "pypy3.8-libs-debuginfo",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "aarch64"
					},
					{
						"name": "pypy3.8",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "aarch64"
					},
					{
						"name": "pypy3.8-debugsource",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "aarch64"
					},
					{
						"name": "pypy3.8-libs",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "aarch64"
					}
				],
				"armv7hl": [
					{
						"name": "pypy3.8",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "armv7hl"
					},
					{
						"name": "pypy3.8-libs-debuginfo",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "armv7hl"
					},
					{
						"name": "pypy3.8-debugsource",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "armv7hl"
					},
					{
						"name": "pypy3.8-libs",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "armv7hl"
					},
					{
						"name": "pypy3.8-devel",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "armv7hl"
					}
				],
				"i686": [
					{
						"name": "pypy3.8-libs-debuginfo",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "i686"
					},
					{
						"name": "pypy3.8",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "i686"
					},
					{
						"name": "pypy3.8-debugsource",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "i686"
					},
					{
						"name": "pypy3.8-libs",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "i686"
					},
					{
						"name": "pypy3.8-devel",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "i686"
					}
				],
				"ppc64le": [
					{
						"name": "pypy3.8",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "ppc64le"
					},
					{
						"name": "pypy3.8-libs-debuginfo",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "ppc64le"
					},
					{
						"name": "pypy3.8-devel",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "ppc64le"
					},
					{
						"name": "pypy3.8-debugsource",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "ppc64le"
					},
					{
						"name": "pypy3.8-libs",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "pypy3.8",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "s390x"
					},
					{
						"name": "pypy3.8-libs",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "s390x"
					},
					{
						"name": "pypy3.8-debugsource",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "s390x"
					},
					{
						"name": "pypy3.8-libs-debuginfo",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "s390x"
					},
					{
						"name": "pypy3.8-devel",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "pypy3.8",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "pypy3.8-libs-debuginfo",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "x86_64"
					},
					{
						"name": "pypy3.8",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "x86_64"
					},
					{
						"name": "pypy3.8-devel",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "x86_64"
					},
					{
						"name": "pypy3.8-debugsource",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "x86_64"
					},
					{
						"name": "pypy3.8-libs",
						"version": "7.3.9",
						"release": "2.3.8.fc36",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 2599659,
			"text": "This update has been submitted for testing by cstratak. ",
			"timestamp": "2022-06-29 18:34:52",
			"update_id": 422800,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2599660,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2022-06-29 18:34:52",
			"update_id": 422800,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2600060,
			"text": "This update has been pushed to testing.",
			"timestamp": "2022-06-30 01:34:03",
			"update_id": 422800,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2607729,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2022-07-07 01:33:06",
			"update_id": 422800,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2608950,
			"text": "This update has been pushed to stable.",
			"timestamp": "2022-07-08 01:16:56",
			"update_id": 422800,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2022-07-08 01:15:45",
	"date_stable": "2022-07-08 01:15:45",
	"date_submitted": "2022-06-29 18:34:52",
	"date_testing": "2022-06-30 01:32:40",
	"meets_testing_requirements": true,
	"notes": "Security fix for CVE-2015-20107",
	"pushed": true,
	"release": {
		"branch": "f36",
		"candidate_tag": "f36-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f36",
		"eol": "2023-05-16",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 36",
		"mail_template": "fedora_errata_template",
		"name": "F36",
		"override_tag": "f36-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f36-signing-pending",
		"pending_stable_tag": "f36-updates-pending",
		"pending_testing_tag": "f36-updates-testing-pending",
		"stable_tag": "f36-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f36-updates-testing",
		"version": "36"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "medium",
	"stable_days": 7,
	"stable_karma": 1,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "pypy3.8-7.3.9-2.3.8.fc36",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2022-b499f2a9c6",
	"unstable_karma": -1,
	"updateid": "FEDORA-2022-b499f2a9c6",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/4bac0f6fccba44f6c476a5dd70dab5ecd3c5fc237db5b9c3af91be34b84a5758?s=24&d=retro",
		"email": "cstratak@redhat.com",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "provenpackager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "modularity-wg"
			},
			{
				"name": "python-packagers-sig"
			}
		],
		"id": 2512,
		"name": "cstratak",
		"openid": "cstratak.id.fedoraproject.org"
	},
	"version_hash": "667dfb64408b71b9e2ca86ff7bb54a1e96f4bf66"
}
